### PR TITLE
Add histogram for health transmission duration

### PR DESCRIPTION
**Pull request by cristinaleonr**
This PR adds a new metric to keep track of how long it takes for the heartbeat to calculate the local health score and send it to the Locate.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/locate/147)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
Thank you for adding this functionality to help us see more clearly into the system.

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/147#-:-N_t2UULBhrDsB348Vww:buz3ijb)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`cmd/heartbeat/main.go` line 135 at r1](https://reviewable.io/reviews/m-lab/locate/147#-N_t14qu7urIm3AVkUZl:-N_t14qu7urIm3AVkUZm:bq9gpqb) ([raw file](https://github.com/m-lab/locate/blob/e8d9637d91707a3098aea60146d092e9bddc4461/cmd/heartbeat/main.go#L135)):*
> ```Go
> 
> 			// Record duration metric.
> 			fmtScore := strconv.FormatFloat(score, 'E', -1, 64)
> ```

What is the cardinality of `score`? If it's only 0/1 right now, please just use 0/1. If it's a float, please limit to 10 values between 0-1 (or 11, I guess).

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/147)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`cmd/heartbeat/main.go` line 135 at r1](https://reviewable.io/reviews/m-lab/locate/147#-N_t14qu7urIm3AVkUZl:-N_t8kB97TtiUDN9u6Qi:bc7svcd) ([raw file](https://github.com/m-lab/locate/blob/e8d9637d91707a3098aea60146d092e9bddc4461/cmd/heartbeat/main.go#L135)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What is the cardinality of `score`? If it's only 0/1 right now, please just use 0/1. If it's a float, please limit to 10 values between 0-1 (or 11, I guess).
</blockquote></details>

Right now it's only 0 or 1. I have updated it to only record one decimal place.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/147#-:-N_t9UK54ieiIgRdW-PR:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by cristinaleonr** [comment]
Related to https://github.com/m-lab/locate/issues/149.

**Pull request merged**
