### PR TITLE
Make Kubernetes metric error generic

### PR DESCRIPTION
**Pull request by cristinaleonr**
The current error status contains a URL like the following:

```
Get "https://api-platform-cluster.mlab-sandbox.measurementlab.net:6443/api/v1/namespaces/default/pods/ndt-virtual-7qzzs": context deadline exceeded
Get "https://api-platform-cluster.mlab-sandbox.measurementlab.net:6443/api/v1/namespaces/default/pods/ndt-virtual-7qzzs": http2: client connection lost
Get "https://api-platform-cluster.mlab-sandbox.measurementlab.net:6443/api/v1/namespaces/default/pods/ndt-virtual-d6zzj": context deadline exceeded
Get "https://api-platform-cluster.mlab-sandbox.measurementlab.net:6443/api/v1/namespaces/default/pods/ndt-virtual-d6zzj": http2: client connection lost
```

This PR makes the error for the metric generic and logs the more specific one.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/locate/88)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/88)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`cmd/heartbeat/health/kubernetes-client.go` line 108 at r1](https://reviewable.io/reviews/m-lab/locate/88#-NGcnyEL3d4QzoDuUvFt:-NGcnyEL3d4QzoDuUvFu:b9p1jss) ([raw file](https://github.com/m-lab/locate/blob/b0df894800830e5a555e1ed853a4224c97a30d21/cmd/heartbeat/health/kubernetes-client.go#L108)):*
> ```Go
> 	if err != nil {
> 		log.Printf("%s: %v", errKubernetesAPI, err)
> 		metrics.KubernetesRequestsTotal.WithLabelValues(errKubernetesAPI).Inc()
> ```

Is it worthwhile distinguishing the error cases in the metric by stripping the pod information and preserving the error details? e.g. "context deadline exceeded" or "http2: client connection lost" ?

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/88)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`cmd/heartbeat/health/kubernetes-client.go` line 108 at r1](https://reviewable.io/reviews/m-lab/locate/88#-NGcnyEL3d4QzoDuUvFt:-NGctbrn7XR2Z-Fs6S1g:bmin9nb) ([raw file](https://github.com/m-lab/locate/blob/b0df894800830e5a555e1ed853a4224c97a30d21/cmd/heartbeat/health/kubernetes-client.go#L108)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is it worthwhile distinguishing the error cases in the metric by stripping the pod information and preserving the error details? e.g. "context deadline exceeded" or "http2: client connection lost" ? 
</blockquote></details>

Thank you for noticing that there was high cardinality data in the original metric label value.

Continuing this thought - are there any other values this metric label could be set to after this change, or will it only be this static value now?

My thought is something like an attempted https://pkg.go.dev/errors#Unwrap - use the inner error if present or the static message otherwise (to prevent extra info).

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/88)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`cmd/heartbeat/health/kubernetes-client.go` line 108 at r1](https://reviewable.io/reviews/m-lab/locate/88#-NGcnyEL3d4QzoDuUvFt:-NGo74YI5fsuBh0H4olf:baygioe) ([raw file](https://github.com/m-lab/locate/blob/b0df894800830e5a555e1ed853a4224c97a30d21/cmd/heartbeat/health/kubernetes-client.go#L108)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Thank you for noticing that there was high cardinality data in the original metric label value.

Continuing this thought - are there any other values this metric label could be set to after this change, or will it only be this static value now?

My thought is something like an attempted https://pkg.go.dev/errors#Unwrap - use the inner error if present or the static message otherwise (to prevent extra info).
</blockquote></details>

Good idea! `Unwrap` returns `nil` for these errors, so I have added functionality to remove the pod/node information.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: - thank you.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/88#-:-NGq4-Hy2Oyzm9p_Bd-Z:b-4ev2s9)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`cmd/heartbeat/health/kubernetes-client.go` line 162 at r2](https://reviewable.io/reviews/m-lab/locate/88#-NGq3jV-0UMWDjiYv7ZI:-NGq3jV-0UMWDjiYv7ZJ:b-dzmmi8) ([raw file](https://github.com/m-lab/locate/blob/c463263c60dd7fd623fba1ec69180477b8aa0b70/cmd/heartbeat/health/kubernetes-client.go#L162)):*
> ```Go
> 	// For errors like "Get 'https://fake-url': context deadline exceeded",
> 	// return the base error without the URL.
> 	if len(parts) == 2 {
> ```

Could this simply be "last element"?

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/88)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`cmd/heartbeat/health/kubernetes-client.go` line 162 at r2](https://reviewable.io/reviews/m-lab/locate/88#-NGq3jV-0UMWDjiYv7ZI:-NGqhNiJB7EUqIPk4aTi:b-896fix) ([raw file](https://github.com/m-lab/locate/blob/c463263c60dd7fd623fba1ec69180477b8aa0b70/cmd/heartbeat/health/kubernetes-client.go#L162)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Could this simply be "last element"?
</blockquote></details>

Done.

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
Sorry, I took another look... 

> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/88#-:-NGqjvGW5Q-eRPb6LPiH:b-cdqwdo)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`cmd/heartbeat/health/kubernetes-client.go` line 162 at r2](https://reviewable.io/reviews/m-lab/locate/88#-NGq3jV-0UMWDjiYv7ZI:-NGqjSPc2wOtasbgtoEZ:b-n81buk) ([raw file](https://github.com/m-lab/locate/blob/c463263c60dd7fd623fba1ec69180477b8aa0b70/cmd/heartbeat/health/kubernetes-client.go#L162)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

if len(parts) >= 2 ...

or more generally, >= 1 would work too.
___
*[`cmd/heartbeat/health/kubernetes-client.go` line 167 at r3](https://reviewable.io/reviews/m-lab/locate/88#-NGqjpfx7sIi3nIGZISr:-NGqjpfx7sIi3nIGZISs:b-o34ybh) ([raw file](https://github.com/m-lab/locate/blob/590ab80652917a1a18c51f9442a30fc0b775017d/cmd/heartbeat/health/kubernetes-client.go#L167)):*
> ```Go
> 
> 	// For unrecognized error formats, return a static message.
> 	return errKubernetesAPI
> ```

Is this reachable?

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/88)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`cmd/heartbeat/health/kubernetes-client.go` line 162 at r2](https://reviewable.io/reviews/m-lab/locate/88#-NGq3jV-0UMWDjiYv7ZI:-NGqm2WL69HIQGrVtmPZ:b-896fix) ([raw file](https://github.com/m-lab/locate/blob/c463263c60dd7fd623fba1ec69180477b8aa0b70/cmd/heartbeat/health/kubernetes-client.go#L162)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

if len(parts) >= 2 ...

or more generally, >= 1 would work too.
</blockquote></details>

Done.
___
*[`cmd/heartbeat/health/kubernetes-client.go` line 167 at r3](https://reviewable.io/reviews/m-lab/locate/88#-NGqjpfx7sIi3nIGZISr:-NGqlIjg55UoLUTJ2CTK:beb2gly) ([raw file](https://github.com/m-lab/locate/blob/590ab80652917a1a18c51f9442a30fc0b775017d/cmd/heartbeat/health/kubernetes-client.go#L167)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is this reachable?
</blockquote></details>

It was before the above condition was changed. Now it's removed.

It was meant to implement your previous comment "use the inner error if present or the static message otherwise (to prevent extra info)." If the error is not of the form "Get 'https://fake-url': context deadline exceeded", we don't know exactly where the inner error is.

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/88)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`cmd/heartbeat/health/kubernetes-client.go` line 167 at r3](https://reviewable.io/reviews/m-lab/locate/88#-NGqjpfx7sIi3nIGZISr:-NGqn-SoAwFhAW_Z10Ml:b6s6d9a) ([raw file](https://github.com/m-lab/locate/blob/590ab80652917a1a18c51f9442a30fc0b775017d/cmd/heartbeat/health/kubernetes-client.go#L167)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

It was before the above condition was changed. Now it's removed.

It was meant to implement your previous comment "use the inner error if present or the static message otherwise (to prevent extra info)." If the error is not of the form "Get 'https://fake-url': context deadline exceeded", we don't know exactly where the inner error is.
</blockquote></details>

Sorry - i feel like we're not communicating easily. My goal was to see if we could preserve some relevant context from the error. I mean to invite you to find the right balance between the trade offs (a static label vs error parsing).
___
*[`cmd/heartbeat/health/kubernetes-client.go` line 156 at r4](https://reviewable.io/reviews/m-lab/locate/88#-NGqnJdj03YQkwDPICFk:-NGqnJdj03YQkwDPICFl:b-myb3pd) ([raw file](https://github.com/m-lab/locate/blob/4b610812b942619135e10d792b1ae70e24ef0242/cmd/heartbeat/health/kubernetes-client.go#L156)):*
> ```Go
> 
> 	// For errors like "context deadline exceeded", return the error as is.
> 	if len(parts) == 1 {
> ```

With the default return path, do we need this condition?
___
*[`cmd/heartbeat/health/kubernetes-client_test.go` line 162 at r2](https://reviewable.io/reviews/m-lab/locate/88#-NGqo0gK8tuI3nLSzotU:-NGqo0gK8tuI3nLSzotV:bfnoezl) ([raw file](https://github.com/m-lab/locate/blob/c463263c60dd7fd623fba1ec69180477b8aa0b70/cmd/heartbeat/health/kubernetes-client_test.go#L162)):*
> ```Go
> 			name: "unrecognized-error-format",
> 			err:  errors.New("error 1: error 2: error 3"),
> 			want: errKubernetesAPI,
> ```

I would keep this case, an want "error 3". Then the tests would cover 1, 2, and 3 field cases.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/88#-:-NGr1Reu8ek77jBKnq0a:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
