### PR TITLE
Add a /v2beta/nearest handler using the V2 Locator

### PR DESCRIPTION
**Pull request by cristinaleonr**
Note: A lot of the line count is due to refactoring and tests, not necessarily new functionality. That said, I'm happy to try to break this down if need be.

________

This PR adds a handler for "/v2beta/nearest" requests.

The OpenAPI configuration can be seen [here](https://api-portal.mlab-sandbox.measurementlab.net/docs/locate-dot-mlab-sandbox.appspot.com/2/introduction).

It also updates the static configuration to use half the [circumference](https://en.wikipedia.org/wiki/Earth%27s_circumference) of the earth (not half the diameter) as the max distance.

Example:
```
Request: https://locate-dot-mlab-sandbox.appspot.com/v2beta/nearest/ndt/ndt7?machine-type=virtual&api_key={API_KEY}

{
  "results": [
    {
      "machine": "mlab1-lax0t.mlab-sandbox.measurement-lab.org",
      "location": {
        "city": "Los Angeles",
        "country": "US"
      },
      "urls": {
        "ws:///ndt/v7/download": "ws://ndt-mlab1-lax0t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtbGF4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NzY2NDU2LCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.9okTCI0R0OZcUR1mQ3g1YT883Pc6rxjbr38YvJD-T33FQK3ccIx96G8VynFPzU3RD3vygWcz44WgGD-ymV6VCw",
        "ws:///ndt/v7/upload": "ws://ndt-mlab1-lax0t.mlab-sandbox.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtbGF4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NzY2NDU2LCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.9okTCI0R0OZcUR1mQ3g1YT883Pc6rxjbr38YvJD-T33FQK3ccIx96G8VynFPzU3RD3vygWcz44WgGD-ymV6VCw",
        "wss:///ndt/v7/download": "wss://ndt-mlab1-lax0t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtbGF4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NzY2NDU2LCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.9okTCI0R0OZcUR1mQ3g1YT883Pc6rxjbr38YvJD-T33FQK3ccIx96G8VynFPzU3RD3vygWcz44WgGD-ymV6VCw",
        "wss:///ndt/v7/upload": "wss://ndt-mlab1-lax0t.mlab-sandbox.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtbGF4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NzY2NDU2LCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.9okTCI0R0OZcUR1mQ3g1YT883Pc6rxjbr38YvJD-T33FQK3ccIx96G8VynFPzU3RD3vygWcz44WgGD-ymV6VCw"
      }
    },
    {
      "machine": "mlab1-chs0t.mlab-sandbox.measurement-lab.org",
      "location": {
        "city": "Charleston",
        "country": "US"
      },
      "urls": {
        "ws:///ndt/v7/download": "ws://ndt-mlab1-chs0t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtY2hzMHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NzY2NDU2LCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.JQtG14YCe5UNQwcrGCVeWd2QeW5Q-Ac0rpO-GZALr7Ct69jfV-ZAfYLFr8764fNUjHKzMz71kTRYxfcTebwtAw",
        "ws:///ndt/v7/upload": "ws://ndt-mlab1-chs0t.mlab-sandbox.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtY2hzMHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NzY2NDU2LCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.JQtG14YCe5UNQwcrGCVeWd2QeW5Q-Ac0rpO-GZALr7Ct69jfV-ZAfYLFr8764fNUjHKzMz71kTRYxfcTebwtAw",
        "wss:///ndt/v7/download": "wss://ndt-mlab1-chs0t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtY2hzMHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NzY2NDU2LCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.JQtG14YCe5UNQwcrGCVeWd2QeW5Q-Ac0rpO-GZALr7Ct69jfV-ZAfYLFr8764fNUjHKzMz71kTRYxfcTebwtAw",
        "wss:///ndt/v7/upload": "wss://ndt-mlab1-chs0t.mlab-sandbox.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtY2hzMHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NzY2NDU2LCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.JQtG14YCe5UNQwcrGCVeWd2QeW5Q-Ac0rpO-GZALr7Ct69jfV-ZAfYLFr8764fNUjHKzMz71kTRYxfcTebwtAw"
      }
    },
    {
      "machine": "mlab1-pdx0t.mlab-sandbox.measurement-lab.org",
      "location": {
        "city": "Portland",
        "country": "US"
      },
      "urls": {
        "ws:///ndt/v7/download": "ws://ndt-mlab1-pdx0t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtcGR4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NzY2NDU2LCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.J53_AGl9QlPJAW0U3KjI0ORPKDBUb64GsM5FXpFzYAhBS2F_L1YSZ9igSNgMUJ1RWxY8oXA_Y0S8SehtxCSjBQ",
        "ws:///ndt/v7/upload": "ws://ndt-mlab1-pdx0t.mlab-sandbox.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtcGR4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NzY2NDU2LCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.J53_AGl9QlPJAW0U3KjI0ORPKDBUb64GsM5FXpFzYAhBS2F_L1YSZ9igSNgMUJ1RWxY8oXA_Y0S8SehtxCSjBQ",
        "wss:///ndt/v7/download": "wss://ndt-mlab1-pdx0t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtcGR4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NzY2NDU2LCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.J53_AGl9QlPJAW0U3KjI0ORPKDBUb64GsM5FXpFzYAhBS2F_L1YSZ9igSNgMUJ1RWxY8oXA_Y0S8SehtxCSjBQ",
        "wss:///ndt/v7/upload": "wss://ndt-mlab1-pdx0t.mlab-sandbox.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtcGR4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NzY2NDU2LCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.J53_AGl9QlPJAW0U3KjI0ORPKDBUb64GsM5FXpFzYAhBS2F_L1YSZ9igSNgMUJ1RWxY8oXA_Y0S8SehtxCSjBQ"
      }
    }
  ]
}
```

This change is [Reviewable](https://reviewable.io/reviews/m-lab/locate/75)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
This all lgtm. The only substantive comment is about the ultimate resource name for the new functionality.

> Reviewed 3 of 7 files at r1, 5 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/75#-:-N7vtlNq2Xcn78ok2M0U:b-3dpcff)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`locate.go` line 171 at r2](https://reviewable.io/reviews/m-lab/locate/75#-N7vt6t732vUdJaYpTXp:-N7vt6t732vUdJaYpTXq:bsjnrhq) ([raw file](https://github.com/m-lab/locate/blob/60a59427965e3a3bbd9aadf5e874cca3a6247a0c/locate.go#L171)):*
> ```Go
> 
> 	// DEPRECATED APIs: TODO: retire after migrating clients.
> 	mux.Handle("/v2/monitoring/", monitoringChain)
> ```

Maybe not this PR - is this resource still in use?
___
*[`locate.go` line 172 at r2](https://reviewable.io/reviews/m-lab/locate/75#-N7vtAa62cSWORdpiAPy:-N7vtAa62cSWORdpiAPz:bpi41ru) ([raw file](https://github.com/m-lab/locate/blob/60a59427965e3a3bbd9aadf5e874cca3a6247a0c/locate.go#L172)):*
> ```Go
> 	// DEPRECATED APIs: TODO: retire after migrating clients.
> 	mux.Handle("/v2/monitoring/", monitoringChain)
> 	mux.HandleFunc("/v2beta1/query/", http.HandlerFunc(c.TranslatedQuery))
> ```

I see ~20 / day in the logs but these clients should have long since migrated. This too can be removed.
___
*[`openapi.yaml` line 154 at r2](https://reviewable.io/reviews/m-lab/locate/75#-N7r3Dzo7FjipGDJOAw2:-N7r3Dzo7FjipGDJOAw3:b-w72ogu) ([raw file](https://github.com/m-lab/locate/blob/60a59427965e3a3bbd9aadf5e874cca3a6247a0c/openapi.yaml#L154)):*
> ```YAML
> 
>   # Beta V2 "nearest" requests WITH an API key.
>   "/v2beta/nearest/{name}/{type}":
> ```

v2beta2?

Also, will this replace the current `/v2/nearest` in time? Can it?

My understanding is that we've intended that only clients with a registered API key would be allowed to make `machine-type` queries. And, the last I knew (this is easily out of date now), api keys were either optional or required (regardless of parameters), and I don't know that I ever encountered hints on making them conditional on specific parameters. Is this possible now? or will we need two resource paths for existing users without api keys and expected users using this new "machine-type query" API?
___
*[`handler/handler.go` line 146 at r2](https://reviewable.io/reviews/m-lab/locate/75#-N7qvVF64hm34sS4s8x4:-N7qvVF64hm34sS4s8x5:b-zakssr) ([raw file](https://github.com/m-lab/locate/blob/60a59427965e3a3bbd9aadf5e874cca3a6247a0c/handler/handler.go#L146)):*
> ```Go
> }
> 
> // Nearest implements /v2beta/nearest requests and uses the LocatorV2 to look up
> ```

nit: I wouldn't mention `/v2beta/nearest` here. That's defined in another file, and is expected to change when we update this to the production version too. You could mention only the LocatorV2 interface or that it's intended for "native" (vs the proxy locator above) lookups using the heartbeat data.
___
*[`handler/handler.go` line 194 at r2](https://reviewable.io/reviews/m-lab/locate/75#-N7vn9L0454-J80JzImf:-N7vn9L0454-J80JzImg:b-5lhud5) ([raw file](https://github.com/m-lab/locate/blob/60a59427965e3a3bbd9aadf5e874cca3a6247a0c/handler/handler.go#L194)):*
> ```Go
> 			Error: v2.NewError("client", errFailedToLookupClient.Error(), status),
> 		}
> 		writeResult(rw, result.Error.Status, &result)
> ```

nit: can the error handling be done in the handler, so one method has all header/status signals in one place?
___
*[`locatetest/locatetest_test.go` line 49 at r2](https://reviewable.io/reviews/m-lab/locate/75#-N7vsK6FARjma5cao3kj:-N7vsK6FARjma5cao3kk:b-xdzywx) ([raw file](https://github.com/m-lab/locate/blob/60a59427965e3a3bbd9aadf5e874cca3a6247a0c/locatetest/locatetest_test.go#L49)):*
> ```Go
> 			ctx := context.Background()
> 			// NOTE: only known services (e.g. ndt/ndt7) are supported by the locate API.
> 			targets, err := c.Nearest(ctx, "ndt/ndt7")
> ```

Okay. This all lgtm. I had to stare at it longer than expected b/c we have a lot of name similarity between the server and the client library.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/75)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`openapi.yaml` line 154 at r2](https://reviewable.io/reviews/m-lab/locate/75#-N7r3Dzo7FjipGDJOAw2:-N7w9s-I2VRbWvYZbtUZ:bchnixk) ([raw file](https://github.com/m-lab/locate/blob/60a59427965e3a3bbd9aadf5e874cca3a6247a0c/openapi.yaml#L154)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

v2beta2?

Also, will this replace the current `/v2/nearest` in time? Can it?

My understanding is that we've intended that only clients with a registered API key would be allowed to make `machine-type` queries. And, the last I knew (this is easily out of date now), api keys were either optional or required (regardless of parameters), and I don't know that I ever encountered hints on making them conditional on specific parameters. Is this possible now? or will we need two resource paths for existing users without api keys and expected users using this new "machine-type query" API?
</blockquote></details>

Changed.

My understanding was that this new handler would eventually replace the one for `/v2/nearest`. I did not realize we wanted to enforce an API key for queries with `machine-type` parameters forever. I thought it was just during testing of this Beta version.

I don't see in the Swagger [documentation](https://swagger.io/docs/specification/2-0/authentication/api-keys/) a way to enforce API keys based on other query parameters :(. 

I suppose we can leave two resource paths. Another option would be to do the replacement but implement some optional authentication mechanism that can be validated in the Locate itself (e.g., if `machine-type`, also check authentication is valid).
___
*[`handler/handler.go` line 146 at r2](https://reviewable.io/reviews/m-lab/locate/75#-N7qvVF64hm34sS4s8x4:-N7w9Zku3UztwT-K-Zbq:b-896fix) ([raw file](https://github.com/m-lab/locate/blob/60a59427965e3a3bbd9aadf5e874cca3a6247a0c/handler/handler.go#L146)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: I wouldn't mention `/v2beta/nearest` here. That's defined in another file, and is expected to change when we update this to the production version too. You could mention only the LocatorV2 interface or that it's intended for "native" (vs the proxy locator above) lookups using the heartbeat data.
</blockquote></details>

Done.
___
*[`handler/handler.go` line 194 at r2](https://reviewable.io/reviews/m-lab/locate/75#-N7vn9L0454-J80JzImf:-N7wBg7h792fD4Lb9Jdu:bwhglds) ([raw file](https://github.com/m-lab/locate/blob/60a59427965e3a3bbd9aadf5e874cca3a6247a0c/handler/handler.go#L194)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: can the error handling be done in the handler, so one method has all header/status signals in one place?
</blockquote></details>

Moved.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/75#-:-N7wMBD8-uYjD964YIb3:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`openapi.yaml` line 154 at r2](https://reviewable.io/reviews/m-lab/locate/75#-N7r3Dzo7FjipGDJOAw2:-N7wLYgo4I1Q1wQvpbxn:b-ci5f80) ([raw file](https://github.com/m-lab/locate/blob/60a59427965e3a3bbd9aadf5e874cca3a6247a0c/openapi.yaml#L154)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Changed.

My understanding was that this new handler would eventually replace the one for `/v2/nearest`. I did not realize we wanted to enforce an API key for queries with `machine-type` parameters forever. I thought it was just during testing of this Beta version.

I don't see in the Swagger [documentation](https://swagger.io/docs/specification/2-0/authentication/api-keys/) a way to enforce API keys based on other query parameters :(. 

I suppose we can leave two resource paths. Another option would be to do the replacement but implement some optional authentication mechanism that can be validated in the Locate itself (e.g., if `machine-type`, also check authentication is valid).
</blockquote></details>

Hmm, could we put this under the `priority` resource eventually? That one requires an API key today. We could ignore this parameter otherwise.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/75)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`openapi.yaml` line 154 at r2](https://reviewable.io/reviews/m-lab/locate/75#-N7r3Dzo7FjipGDJOAw2:-N7wNM2307aB-m-0KbMu:b-6o4q62) ([raw file](https://github.com/m-lab/locate/blob/60a59427965e3a3bbd9aadf5e874cca3a6247a0c/openapi.yaml#L154)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Hmm, could we put this under the `priority` resource eventually? That one requires an API key today. We could ignore this parameter otherwise.
</blockquote></details>

Great idea! Yes, that would work.

**Pull request merged**
