### PR TITLE
Add new v2 location functionality

### PR DESCRIPTION
**Pull request by cristinaleonr**
Note: Regarding the line count, only ~200 lines are actual code. The rest is unit tests.

---------------

This PR adds a new  v2 implementation of a `Locator`. The full changes were tested using docker-compose. 

Request: localhost:8080/v2beta/nearest/ndt/ndt7?region=US-NY

Response:

```
{
  "results": [
    {
      "machine": "mlab2-lga1t.mlab-sandbox.measurement-lab.org",
      "location": {
        "city": "New York",
        "country": "US"
      },
      "urls": {
        "ws:///ndt/v7/download": "ws://ndt-mlab2-lga1t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6InVuaXR0ZXN0XzIwMjIwNDE1In0.eyJhdWQiOlsibWxhYjItbGdhMXQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NDYyNTgyLCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.hebgwTeevge850Ty5Ylt-yahkgJ_O741xUFNQjGjkYKyPa4j55XaMROSYL9keneEs6Raf9sD0f0QdvLmeNitCQ",
        "ws:///ndt/v7/upload": "ws://ndt-mlab2-lga1t.mlab-sandbox.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6InVuaXR0ZXN0XzIwMjIwNDE1In0.eyJhdWQiOlsibWxhYjItbGdhMXQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NDYyNTgyLCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.hebgwTeevge850Ty5Ylt-yahkgJ_O741xUFNQjGjkYKyPa4j55XaMROSYL9keneEs6Raf9sD0f0QdvLmeNitCQ",
        "wss:///ndt/v7/download": "wss://ndt-mlab2-lga1t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6InVuaXR0ZXN0XzIwMjIwNDE1In0.eyJhdWQiOlsibWxhYjItbGdhMXQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NDYyNTgyLCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.hebgwTeevge850Ty5Ylt-yahkgJ_O741xUFNQjGjkYKyPa4j55XaMROSYL9keneEs6Raf9sD0f0QdvLmeNitCQ",
        "wss:///ndt/v7/upload": "wss://ndt-mlab2-lga1t.mlab-sandbox.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6InVuaXR0ZXN0XzIwMjIwNDE1In0.eyJhdWQiOlsibWxhYjItbGdhMXQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NDYyNTgyLCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.hebgwTeevge850Ty5Ylt-yahkgJ_O741xUFNQjGjkYKyPa4j55XaMROSYL9keneEs6Raf9sD0f0QdvLmeNitCQ"
      }
    },
    {
      "machine": "mlab1-pdx0t.mlab-sandbox.measurement-lab.org",
      "location": {
        "city": "Portland",
        "country": "US"
      },
      "urls": {
        "ws:///ndt/v7/download": "ws://ndt-mlab1-pdx0t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6InVuaXR0ZXN0XzIwMjIwNDE1In0.eyJhdWQiOlsibWxhYjEtcGR4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NDYyNTgyLCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.voEY2aHxHS3CgXXL2dDuhTlakIEddzBB3PaNiJHjxYrA_fJF_6-crB05QLjkpX-s7jmrYj8wU9gJuyqgBjoxCQ",
        "ws:///ndt/v7/upload": "ws://ndt-mlab1-pdx0t.mlab-sandbox.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6InVuaXR0ZXN0XzIwMjIwNDE1In0.eyJhdWQiOlsibWxhYjEtcGR4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NDYyNTgyLCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.voEY2aHxHS3CgXXL2dDuhTlakIEddzBB3PaNiJHjxYrA_fJF_6-crB05QLjkpX-s7jmrYj8wU9gJuyqgBjoxCQ",
        "wss:///ndt/v7/download": "wss://ndt-mlab1-pdx0t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6InVuaXR0ZXN0XzIwMjIwNDE1In0.eyJhdWQiOlsibWxhYjEtcGR4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NDYyNTgyLCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.voEY2aHxHS3CgXXL2dDuhTlakIEddzBB3PaNiJHjxYrA_fJF_6-crB05QLjkpX-s7jmrYj8wU9gJuyqgBjoxCQ",
        "wss:///ndt/v7/upload": "wss://ndt-mlab1-pdx0t.mlab-sandbox.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6InVuaXR0ZXN0XzIwMjIwNDE1In0.eyJhdWQiOlsibWxhYjEtcGR4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NDYyNTgyLCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.voEY2aHxHS3CgXXL2dDuhTlakIEddzBB3PaNiJHjxYrA_fJF_6-crB05QLjkpX-s7jmrYj8wU9gJuyqgBjoxCQ"
      }
    },
    {
      "machine": "mlab1-lga0t.mlab-sandbox.measurement-lab.org",
      "location": {
        "city": "New York",
        "country": "US"
      },
      "urls": {
        "ws:///ndt/v7/download": "ws://ndt-mlab1-lga0t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6InVuaXR0ZXN0XzIwMjIwNDE1In0.eyJhdWQiOlsibWxhYjEtbGdhMHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NDYyNTgyLCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.pkPGAJcTeaQf29sYUx6lLgX49f4nMEdd0Te_tMhlAZ_GwOxOAt4FwTxqkXFdagUlrOQhTkhOmy17KgUiqYdADw",
        "ws:///ndt/v7/upload": "ws://ndt-mlab1-lga0t.mlab-sandbox.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6InVuaXR0ZXN0XzIwMjIwNDE1In0.eyJhdWQiOlsibWxhYjEtbGdhMHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NDYyNTgyLCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.pkPGAJcTeaQf29sYUx6lLgX49f4nMEdd0Te_tMhlAZ_GwOxOAt4FwTxqkXFdagUlrOQhTkhOmy17KgUiqYdADw",
        "wss:///ndt/v7/download": "wss://ndt-mlab1-lga0t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6InVuaXR0ZXN0XzIwMjIwNDE1In0.eyJhdWQiOlsibWxhYjEtbGdhMHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NDYyNTgyLCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.pkPGAJcTeaQf29sYUx6lLgX49f4nMEdd0Te_tMhlAZ_GwOxOAt4FwTxqkXFdagUlrOQhTkhOmy17KgUiqYdADw",
        "wss:///ndt/v7/upload": "wss://ndt-mlab1-lga0t.mlab-sandbox.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6InVuaXR0ZXN0XzIwMjIwNDE1In0.eyJhdWQiOlsibWxhYjEtbGdhMHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NDYyNTgyLCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.pkPGAJcTeaQf29sYUx6lLgX49f4nMEdd0Te_tMhlAZ_GwOxOAt4FwTxqkXFdagUlrOQhTkhOmy17KgUiqYdADw"
      }
    },
    {
      "machine": "mlab1-lax0t.mlab-sandbox.measurement-lab.org",
      "location": {
        "city": "Los Angeles",
        "country": "US"
      },
      "urls": {
        "ws:///ndt/v7/download": "ws://ndt-mlab1-lax0t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6InVuaXR0ZXN0XzIwMjIwNDE1In0.eyJhdWQiOlsibWxhYjEtbGF4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NDYyNTgyLCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.2qtfCbUnK1A6jhcnVypIEdT2N6xknP07sEe8ioAaZUyqnaIFRBjllshprj-3IvGuYOAHHujH2B3toNqA5YfwBw",
        "ws:///ndt/v7/upload": "ws://ndt-mlab1-lax0t.mlab-sandbox.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6InVuaXR0ZXN0XzIwMjIwNDE1In0.eyJhdWQiOlsibWxhYjEtbGF4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NDYyNTgyLCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.2qtfCbUnK1A6jhcnVypIEdT2N6xknP07sEe8ioAaZUyqnaIFRBjllshprj-3IvGuYOAHHujH2B3toNqA5YfwBw",
        "wss:///ndt/v7/download": "wss://ndt-mlab1-lax0t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6InVuaXR0ZXN0XzIwMjIwNDE1In0.eyJhdWQiOlsibWxhYjEtbGF4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NDYyNTgyLCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.2qtfCbUnK1A6jhcnVypIEdT2N6xknP07sEe8ioAaZUyqnaIFRBjllshprj-3IvGuYOAHHujH2B3toNqA5YfwBw",
        "wss:///ndt/v7/upload": "wss://ndt-mlab1-lax0t.mlab-sandbox.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6InVuaXR0ZXN0XzIwMjIwNDE1In0.eyJhdWQiOlsibWxhYjEtbGF4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjU4NDYyNTgyLCJpc3MiOiJsb2NhdGUiLCJzdWIiOiJuZHQifQ.2qtfCbUnK1A6jhcnVypIEdT2N6xknP07sEe8ioAaZUyqnaIFRBjllshprj-3IvGuYOAHHujH2B3toNqA5YfwBw"
      }
    }
  ]
}
```

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/locate/74)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
Awesome.

> Reviewed 3 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/74#-:-N7alGFB0954O3O2G4-e:bccpe8g)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`heartbeat/heartbeat.go` line 83 at r2](https://reviewable.io/reviews/m-lab/locate/74#-N7aZAAODHfBdKGfWMjf:-N7aZAAODHfBdKGfWMjg:b85qbeu) ([raw file](https://github.com/m-lab/locate/blob/9757aa19e969730542582debf26c659426d447d8/heartbeat/heartbeat.go#L83)):*
> ```Go
> // their values.
> func (h *heartbeatStatusTracker) Instances() map[string]v2.HeartbeatMessage {
> 	return h.instances
> ```

Since this returns a pointer to the internal map, there will be races with future updates of this type. Consider adding a `-race` test to discover and prevent this.
___
*[`location/location.go` line 20 at r2](https://reviewable.io/reviews/m-lab/locate/74#-N7a_mx_-3dVZJBVKmIN:-N7a_mx_-3dVZJBVKmIO:bvvvtwe) ([raw file](https://github.com/m-lab/locate/blob/9757aa19e969730542582debf26c659426d447d8/location/location.go#L20)):*
> ```Go
> 
> // Locator manages requests to "locate" mlab-ns servers.
> type Locator struct {
> ```

nit: location.Locator

The proxy.Locator signals that its from another source.. I could see this in `heartbeat.Locator` -- it signals that the location is derived from the heartbeat data. What do you think?
___
*[`location/location.go` line 40 at r2](https://reviewable.io/reviews/m-lab/locate/74#-N7aastO7bl_pMH1NqH5:-N7aastO7bl_pMH1NqH6:bbgt85a) ([raw file](https://github.com/m-lab/locate/blob/9757aa19e969730542582debf26c659426d447d8/location/location.go#L40)):*
> ```Go
> func NewServerLocator(tracker handler.StatusTracker) *Locator {
> 	return &Locator{
> 		StatusTracker: tracker,
> ```

Hmm, I imagine the current package as a dependency for the handler logic not the other way around. If the current package were in the heartbeat package, we could define this interface there. This would be the first users of that interface so defend placing the interface definition there, and the handler package could import this instead.
___
*[`location/location.go` line 46 at r2](https://reviewable.io/reviews/m-lab/locate/74#-N7acq-a8LDutT4ji5gl:-N7acq-a8LDutT4ji5gm:b4zhcrb) ([raw file](https://github.com/m-lab/locate/blob/9757aa19e969730542582debf26c659426d447d8/location/location.go#L46)):*
> ```Go
> // Nearest discovers the nearest machines for the target service, using
> // an exponentially distributed function based on distance.
> func (l *Locator) Nearest(service, t string, lat, lon float64) ([]v2.Target, []url.URL, error) {
> ```

Super clear logic. :+1: 
___
*[`location/location.go` line 54 at r2](https://reviewable.io/reviews/m-lab/locate/74#-N7ajJq69NoCU7Hoyuqe:-N7ajJq69NoCU7Hoyuqf:bfkd9h4) ([raw file](https://github.com/m-lab/locate/blob/9757aa19e969730542582debf26c659426d447d8/location/location.go#L54)):*
> ```Go
> 
> 	// Pick.
> 	targets, urls := pickTargets(service, sites, time.Now().UnixNano())
> ```

Hmm, I'm not sure about the wisdom of choosing a new seed every time.. this isn't crypto, but in that context, this would make the value more predictable.. even in non-crypto scenarios, I'm inclined to recommend that we choose a seed once for a process. Maybe `r := mathx.NewRandom(seed)` as a package variable?
___
*[`location/location.go` line 74 at r2](https://reviewable.io/reviews/m-lab/locate/74#-N7aes6jE80Cbv73HpD0:-N7aes6jE80Cbv73HpD1:b-6zdi4w) ([raw file](https://github.com/m-lab/locate/blob/9757aa19e969730542582debf26c659426d447d8/location/location.go#L74)):*
> ```Go
> 		}
> 
> 		registration := v.Registration
> ```

nit: prefer shorter variable names, like "reg" or even "r" here.

I think I'm channeling what a go readability reviewer might say here. The full name for the struct field is correct. For ephemeral local variables, shorter seems to be generally preferable. https://github.com/golang/go/wiki/CodeReviewComments#variable-names

I'll acknowledge that we don't do this consistently throughout m-lab and it's a gray area where the line is between short/long/clear. In this case, I'm confident we don't need the hole name.

Also, I would recommend a slightly longer parameter name for `t` to Nearest above. I wasn't quite sure what that was until `isValidInstance` comparison to `Type.` That one is arguably on the wrong side of too short or unclear. :) 
___
*[`location/location.go` line 84 at r2](https://reviewable.io/reviews/m-lab/locate/74#-N7ahINtC6Oh8-qSWFo8:-N7ahINtC6Oh8-qSWFo9:b-pr3ve7) ([raw file](https://github.com/m-lab/locate/blob/9757aa19e969730542582debf26c659426d447d8/location/location.go#L84)):*
> ```Go
> 			// TODO: does it make sense to reuse the registration for sites or
> 			// to create a new struct?
> 			s.registration.Experiment = ""
> ```

I'm not sure I understand what this is doing. (I think I understand clearing Hostname/Machine for an aggregation by "site").
___
*[`location/location.go` line 113 at r2](https://reviewable.io/reviews/m-lab/locate/74#-N7aec8vArMp5uuLP49Z:-N7aec8vArMp5uuLP49_:b-afarlm) ([raw file](https://github.com/m-lab/locate/blob/9757aa19e969730542582debf26c659426d447d8/location/location.go#L113)):*
> ```Go
> 	}
> 
> 	if t != "" && t != registration.Type {
> ```

what is type?
___
*[`location/location.go` line 124 at r2](https://reviewable.io/reviews/m-lab/locate/74#-N7aeMJHCeipzeGpD1kh:-N7aeMJHCeipzeGpD1ki:b-oj4pz6) ([raw file](https://github.com/m-lab/locate/blob/9757aa19e969730542582debf26c659426d447d8/location/location.go#L124)):*
> ```Go
> 	// It might require implementing a reverse geocoder.
> 	distance := mathx.GetHaversineDistance(lat, lon, registration.Latitude, registration.Longitude)
> 	if distance > static.EarthRadiusKm {
> ```

:+1: this is good; please document this policy decision in the design doc if not already there. This is the first time we're adding a limit iirc.
___
*[`location/location.go` line 165 at r2](https://reviewable.io/reviews/m-lab/locate/74#-N7akT6j3-GYvoC_B-lD:-N7akT6j3-GYvoC_B-lE:b-y1ab3o) ([raw file](https://github.com/m-lab/locate/blob/9757aa19e969730542582debf26c659426d447d8/location/location.go#L165)):*
> ```Go
> 			URLs: make(map[string]string),
> 		}
> 		sites = append(sites[:index], sites[index+1:]...)
> ```

Please add a comment that this is removing the selected site from the set of candidate sites for the next target selection.

This concatenation may be a memory/cpu expensive operation... Doesn't matter for v0, but make a mental note.

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/74)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`location/location.go` line 113 at r2](https://reviewable.io/reviews/m-lab/locate/74#-N7aec8vArMp5uuLP49Z:-N7alZdW-Jul5HutwErC:b5l0llh) ([raw file](https://github.com/m-lab/locate/blob/9757aa19e969730542582debf26c659426d447d8/location/location.go#L113)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

what is type?
</blockquote></details>

this was a note to myself... disregard.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/74)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`heartbeat/heartbeat.go` line 83 at r2](https://reviewable.io/reviews/m-lab/locate/74#-N7aZAAODHfBdKGfWMjf:-N7b8q9s275IaQBWmorL:b-xhngv6) ([raw file](https://github.com/m-lab/locate/blob/9757aa19e969730542582debf26c659426d447d8/heartbeat/heartbeat.go#L83)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Since this returns a pointer to the internal map, there will be races with future updates of this type. Consider adding a `-race` test to discover and prevent this.
</blockquote></details>

Whoops, forgot this was pass by reference. 

I'm returning a copy now and added a test to make sure updates are not reflected in the value returned here.
___
*[`location/location.go` line 20 at r2](https://reviewable.io/reviews/m-lab/locate/74#-N7a_mx_-3dVZJBVKmIN:-N7b8NwFAcpH1m7Jzkl-:b5ptbdy) ([raw file](https://github.com/m-lab/locate/blob/9757aa19e969730542582debf26c659426d447d8/location/location.go#L20)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: location.Locator

The proxy.Locator signals that its from another source.. I could see this in `heartbeat.Locator` -- it signals that the location is derived from the heartbeat data. What do you think?
</blockquote></details>

Moved to the `heartbeat` package.
___
*[`location/location.go` line 40 at r2](https://reviewable.io/reviews/m-lab/locate/74#-N7aastO7bl_pMH1NqH5:-N7b8VZM4eRbG8fcOV42:b-jrdubp) ([raw file](https://github.com/m-lab/locate/blob/9757aa19e969730542582debf26c659426d447d8/location/location.go#L40)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Hmm, I imagine the current package as a dependency for the handler logic not the other way around. If the current package were in the heartbeat package, we could define this interface there. This would be the first users of that interface so defend placing the interface definition there, and the handler package could import this instead.
</blockquote></details>

I really like this. Moved.
___
*[`location/location.go` line 54 at r2](https://reviewable.io/reviews/m-lab/locate/74#-N7ajJq69NoCU7Hoyuqe:-N7bF9Md1UnAWndBOkRN:b2rah3u) ([raw file](https://github.com/m-lab/locate/blob/9757aa19e969730542582debf26c659426d447d8/location/location.go#L54)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Hmm, I'm not sure about the wisdom of choosing a new seed every time.. this isn't crypto, but in that context, this would make the value more predictable.. even in non-crypto scenarios, I'm inclined to recommend that we choose a seed once for a process. Maybe `r := mathx.NewRandom(seed)` as a package variable?
</blockquote></details>

Makes sense. Changed.
___
*[`location/location.go` line 74 at r2](https://reviewable.io/reviews/m-lab/locate/74#-N7aes6jE80Cbv73HpD0:-N7b7hTh0CPs1cGJU9fM:b-ouwsk8) ([raw file](https://github.com/m-lab/locate/blob/9757aa19e969730542582debf26c659426d447d8/location/location.go#L74)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: prefer shorter variable names, like "reg" or even "r" here.

I think I'm channeling what a go readability reviewer might say here. The full name for the struct field is correct. For ephemeral local variables, shorter seems to be generally preferable. https://github.com/golang/go/wiki/CodeReviewComments#variable-names

I'll acknowledge that we don't do this consistently throughout m-lab and it's a gray area where the line is between short/long/clear. In this case, I'm confident we don't need the hole name.

Also, I would recommend a slightly longer parameter name for `t` to Nearest above. I wasn't quite sure what that was until `isValidInstance` comparison to `Type.` That one is arguably on the wrong side of too short or unclear. :) 

</blockquote></details>

I had `r` at first and then wrote out the whole word because I thought it might be confusing with so many short variables (e.g., `m`, `s`, `t`). Changed now.

I agree about `t`. I did it because `type` is a Go keyword, so it can't be used. Hopefully `typ` is more helpful.
___
*[`location/location.go` line 84 at r2](https://reviewable.io/reviews/m-lab/locate/74#-N7ahINtC6Oh8-qSWFo8:-N7bIcbPDDZ1dzTlSMFX:b-66yzih) ([raw file](https://github.com/m-lab/locate/blob/9757aa19e969730542582debf26c659426d447d8/location/location.go#L84)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I'm not sure I understand what this is doing. (I think I understand clearing Hostname/Machine for an aggregation by "site").
</blockquote></details>

It was clearing the experiment because, technically, in the real world, m-lab sites don't have just one experiment.

As you said, in this case, they will share the same experiment given the client request, so it makes sense to leave it. Updated!
___
*[`location/location.go` line 124 at r2](https://reviewable.io/reviews/m-lab/locate/74#-N7aeMJHCeipzeGpD1kh:-N7b751JBbvIpOl8D6-q:bqmjwcz) ([raw file](https://github.com/m-lab/locate/blob/9757aa19e969730542582debf26c659426d447d8/location/location.go#L124)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

:+1: this is good; please document this policy decision in the design doc if not already there. This is the first time we're adding a limit iirc.
</blockquote></details>

Added.
___
*[`location/location.go` line 165 at r2](https://reviewable.io/reviews/m-lab/locate/74#-N7akT6j3-GYvoC_B-lD:-N7b77uk6mWWU7X72BsL:bcy92l7) ([raw file](https://github.com/m-lab/locate/blob/9757aa19e969730542582debf26c659426d447d8/location/location.go#L165)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add a comment that this is removing the selected site from the set of candidate sites for the next target selection.

This concatenation may be a memory/cpu expensive operation... Doesn't matter for v0, but make a mental note.
</blockquote></details>

Added.

Yep, I thought about the fact that this is a linear operation when I added it. That said, if I didn't remove the site, subsequent selections would get more complicated. I'm open to suggestions.

**Review by stephen-soltesz — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 3 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/74)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`heartbeat/heartbeat.go` line 83 at r2](https://reviewable.io/reviews/m-lab/locate/74#-N7aZAAODHfBdKGfWMjf:-N7bLCpl7Uw3LBxoX3u8:b-ge63lg) ([raw file](https://github.com/m-lab/locate/blob/9757aa19e969730542582debf26c659426d447d8/heartbeat/heartbeat.go#L83)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Whoops, forgot this was pass by reference. 

I'm returning a copy now and added a test to make sure updates are not reflected in the value returned here.
</blockquote></details>

:+1: please use a different variable name. `copy` is a builtin function.
___
*[`heartbeat/location_test.go` line 57 at r3](https://reviewable.io/reviews/m-lab/locate/74#-N7bNtJK47P0LGlq-7_0:-N7bNtJK47P0LGlq-7_1:b-raq5z5) ([raw file](https://github.com/m-lab/locate/blob/fd9fff8c6db7a2892f7e2b31f84a1c0a809f0369/heartbeat/location_test.go#L57)):*
> ```Go
> 			ContinentCode: "NA",
> 			Experiment:    "ndt",
> 			Hostname:      "ndt-mlab1-lga0t.mlab-sandbox.measurement-lab.org",
> ```

nit: to avoid some confusion, prefer a fake site name or a site name that is currently configured as a virtual node. In this case calling lga0t (physical in reality) a virtual site for testing could make a casual reader might miss the Type difference and assume it will match reality.

So, short summary: either reflect reality or make up a new names entirely to prevent confusion.
___
*[`heartbeat/location_test.go` line 190 at r3](https://reviewable.io/reviews/m-lab/locate/74#-N7bOji32Pa1w4hL5dhf:-N7bOji32Pa1w4hL5dhg:b-74bja7) ([raw file](https://github.com/m-lab/locate/blob/fd9fff8c6db7a2892f7e2b31f84a1c0a809f0369/heartbeat/location_test.go#L190)):*
> ```Go
> 		machines: []machine{
> 			{
> 				name:   "name:mlab1-pdx01.mlab-sandbox.measurement-lab.org",
> ```

is this name string correct? `virtualSite` above has the same thing but physicalSite does not.
___
*[`heartbeat/location_test.go` line 233 at r3](https://reviewable.io/reviews/m-lab/locate/74#-N7bP6ag0W0TThpn7q-c:-N7bP6ag0W0TThpn7q-d:b8h1v2h) ([raw file](https://github.com/m-lab/locate/blob/fd9fff8c6db7a2892f7e2b31f84a1c0a809f0369/heartbeat/location_test.go#L233)):*
> ```Go
> 		name            string
> 		service         string
> 		t               string
> ```

t -> typ. or mtype or similar.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/74)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`heartbeat/heartbeat.go` line 83 at r2](https://reviewable.io/reviews/m-lab/locate/74#-N7aZAAODHfBdKGfWMjf:-N7bjsw10PaDHqqNhNrR:b-a2ujfl) ([raw file](https://github.com/m-lab/locate/blob/9757aa19e969730542582debf26c659426d447d8/heartbeat/heartbeat.go#L83)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

:+1: please use a different variable name. `copy` is a builtin function.
</blockquote></details>

Changed.
___
*[`heartbeat/location_test.go` line 57 at r3](https://reviewable.io/reviews/m-lab/locate/74#-N7bNtJK47P0LGlq-7_0:-N7bk6kSDDHpRmxKs7se:b-gosuew) ([raw file](https://github.com/m-lab/locate/blob/fd9fff8c6db7a2892f7e2b31f84a1c0a809f0369/heartbeat/location_test.go#L57)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: to avoid some confusion, prefer a fake site name or a site name that is currently configured as a virtual node. In this case calling lga0t (physical in reality) a virtual site for testing could make a casual reader might miss the Type difference and assume it will match reality.

So, short summary: either reflect reality or make up a new names entirely to prevent confusion.
</blockquote></details>

I've updated them to fake site names.
___
*[`heartbeat/location_test.go` line 190 at r3](https://reviewable.io/reviews/m-lab/locate/74#-N7bOji32Pa1w4hL5dhf:-N7bkG0F8YK-KGR4-oCV:b-lxjkco) ([raw file](https://github.com/m-lab/locate/blob/fd9fff8c6db7a2892f7e2b31f84a1c0a809f0369/heartbeat/location_test.go#L190)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

is this name string correct? `virtualSite` above has the same thing but physicalSite does not.
</blockquote></details>

Good catch!

`deep.Equal()` was also not detecting the difference in strings, so I have changed the test check to use`reflect.DeepEqual()`, which does.
___
*[`heartbeat/location_test.go` line 233 at r3](https://reviewable.io/reviews/m-lab/locate/74#-N7bP6ag0W0TThpn7q-c:-N7bkSp26_Kh0yjE1mdM:bwrufxd) ([raw file](https://github.com/m-lab/locate/blob/fd9fff8c6db7a2892f7e2b31f84a1c0a809f0369/heartbeat/location_test.go#L233)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

t -> typ. or mtype or similar.
</blockquote></details>

You're right. Updated.

**Review by stephen-soltesz — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/74)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
