### PR TITLE
Pass in hostname to Prometheus single instance update

### PR DESCRIPTION
**Pull request by cristinaleonr**
This PR fixes the parameter for the single instance Prometheus update to be the Hostname.

This fixes the error: `Error parsing hostname mlab2`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/locate/205)

### CODE REVIEW

**Review by nkinkade — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/205)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`handler/heartbeat.go` line 79 at r1](https://reviewable.io/reviews/m-lab/locate/205#-OBRbYwL59zm0CpEEkn6:-OBRbYwMD1ICmISGHviU:b-opbawi) ([raw file](https://github.com/m-lab/locate/blob/36397d7470a9ff5497aa6c67e8fe336922ec4e90/handler/heartbeat.go#L79)):*
> ```Go
> 
> 				// Update Prometheus signals every time a Registration message is received.
> 				c.promRegistration(context.Background(), hbm.Registration.Hostname)
> ```

I am likely missing something, but why a whole new function `promRegistration()`?  Wouldn't just passing `hbm.Registration.Hostname` to  the "hostname" parameter of `updatePrometheusForMachine()` do effectively the same thing?

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/205)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[`handler/heartbeat.go` line 79 at r1](https://reviewable.io/reviews/m-lab/locate/205#-OBRbYwL59zm0CpEEkn6:-OBRe4NG3dDtl_bPvnvt:bdcln9o) ([raw file](https://github.com/m-lab/locate/blob/36397d7470a9ff5497aa6c67e8fe336922ec4e90/handler/heartbeat.go#L79)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I am likely missing something, but why a whole new function `promRegistration()`?  Wouldn't just passing `hbm.Registration.Hostname` to  the "hostname" parameter of `updatePrometheusForMachine()` do effectively the same thing?
</blockquote></details>

You're right, it could be as simple as that. I just wanted to add some testing to ensure this isn't missed in the future.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/205)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[`handler/heartbeat.go` line 79 at r1](https://reviewable.io/reviews/m-lab/locate/205#-OBRbYwL59zm0CpEEkn6:-OBRm4BMDFGLwPFKJkNc:btp526h) ([raw file](https://github.com/m-lab/locate/blob/36397d7470a9ff5497aa6c67e8fe336922ec4e90/handler/heartbeat.go#L79)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

You're right, it could be as simple as that. I just wanted to add some testing to ensure this isn't missed in the future.
</blockquote></details>

Actually, that was not a very good test to begin with. I removed the function and just updated the parameter.

**Review by nkinkade — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/205)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

**Pull request merged**
