### PR TITLE
Add timeout for /health endpoint checks

### PR DESCRIPTION
**Pull request by cristinaleonr**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/locate/145)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/145)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`cmd/heartbeat/health/checker_test.go` line 28 at r1](https://reviewable.io/reviews/m-lab/locate/145#-N_opnHL12xmnvyGQLz2:-N_opnHL12xmnvyGQLz3:bjz4na2) ([raw file](https://github.com/m-lab/locate/blob/65d7951949aae2cb2d1d45c8ac1a8fb05995d9a3/cmd/heartbeat/health/checker_test.go#L28)):*
> ```Go
> 				},
> 				&EndpointClient{
> 					Client: http.Client{},
> ```

nit: the Client value is a literal (not a pointer) and the zero value for `http.Client` is what's being declared here. Is it sufficient to simply declare `&EndpointClient{}` here?
___
*[`cmd/heartbeat/health/checker_test.go` line 151 at r1](https://reviewable.io/reviews/m-lab/locate/145#-N_oqEoS2rh25FpXy5Kg:-N_oqEoS2rh25FpXy5Kh:b-b9a40t) ([raw file](https://github.com/m-lab/locate/blob/65d7951949aae2cb2d1d45c8ac1a8fb05995d9a3/cmd/heartbeat/health/checker_test.go#L151)):*
> ```Go
> 				},
> 				&EndpointClient{
> 					Client: http.Client{},
> ```

Do any of these cases induce a timeout event for the health endpoint client? Which one if so? Please add one if not. This is the functionality being added. One test verifying that behavior would be welcome.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/145)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`cmd/heartbeat/health/checker_test.go` line 28 at r1](https://reviewable.io/reviews/m-lab/locate/145#-N_opnHL12xmnvyGQLz2:-N_oylLjASKIOQvMkzsc:b-a2ujfl) ([raw file](https://github.com/m-lab/locate/blob/65d7951949aae2cb2d1d45c8ac1a8fb05995d9a3/cmd/heartbeat/health/checker_test.go#L28)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: the Client value is a literal (not a pointer) and the zero value for `http.Client` is what's being declared here. Is it sufficient to simply declare `&EndpointClient{}` here?
</blockquote></details>

Changed.
___
*[`cmd/heartbeat/health/checker_test.go` line 151 at r1](https://reviewable.io/reviews/m-lab/locate/145#-N_oqEoS2rh25FpXy5Kg:-N_oyoUTEYZ1keK1txve:b-5dol3m) ([raw file](https://github.com/m-lab/locate/blob/65d7951949aae2cb2d1d45c8ac1a8fb05995d9a3/cmd/heartbeat/health/checker_test.go#L151)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Do any of these cases induce a timeout event for the health endpoint client? Which one if so? Please add one if not. This is the functionality being added. One test verifying that behavior would be welcome.
</blockquote></details>

I have added a test in the test file for the class where the behavior was implemented.

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/145)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`cmd/heartbeat/health/endpoint-check_test.go` line 55 at r2](https://reviewable.io/reviews/m-lab/locate/145#-N_p-WvRC1C7LBSr9c-l:-N_p-WvRC1C7LBSr9c-m:b854bl3) ([raw file](https://github.com/m-lab/locate/blob/0f4e7a99346bf6cf8208a78fcddb95a8eb6bdfac/cmd/heartbeat/health/endpoint-check_test.go#L55)):*
> ```Go
> 			}
> 
> 			hc := NewEndpointClient(time.Second)
> ```

Where is `tt.timeout` used?

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/145)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`cmd/heartbeat/health/endpoint-check_test.go` line 55 at r2](https://reviewable.io/reviews/m-lab/locate/145#-N_p-WvRC1C7LBSr9c-l:-N_p6Et850o1RJjHqsnL:bbw4kfr) ([raw file](https://github.com/m-lab/locate/blob/0f4e7a99346bf6cf8208a78fcddb95a8eb6bdfac/cmd/heartbeat/health/endpoint-check_test.go#L55)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Where is `tt.timeout` used?
</blockquote></details>

Whoops, sorry! The test was passing for a different reason, which I have now fixed.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/145)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`cmd/heartbeat/health/endpoint-check_test.go` line 55 at r2](https://reviewable.io/reviews/m-lab/locate/145#-N_p-WvRC1C7LBSr9c-l:-N_p7PmV3GR_iArsw9K2:b8b3t1) ([raw file](https://github.com/m-lab/locate/blob/0f4e7a99346bf6cf8208a78fcddb95a8eb6bdfac/cmd/heartbeat/health/endpoint-check_test.go#L55)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Whoops, sorry! The test was passing for a different reason, which I have now fixed.
</blockquote></details>

Nvm, wait.

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/145)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`cmd/heartbeat/health/endpoint-check_test.go` line 31 at r3](https://reviewable.io/reviews/m-lab/locate/145#-N_p7L3DAuDVUFvHiRiM:-N_p7L3DAuDVUFvHiRiN:bak4j4r) ([raw file](https://github.com/m-lab/locate/blob/fc403555f89cd97e8bfdf6b2218f44ded46beaaf/cmd/heartbeat/health/endpoint-check_test.go#L31)):*
> ```Go
> 			name:     "timeout",
> 			code:     http.StatusOK,
> 			timeout:  0,
> ```

This error case is labeled "timeout" -- but iiuc, an `http.Client` behavior with timeout = 0 is no timeout. What is this case testing?
___
*[`cmd/heartbeat/health/endpoint-check_test.go` line 45 at r3](https://reviewable.io/reviews/m-lab/locate/145#-N_p7t8zCZ_fXl3Meeug:-N_p7t8zCZ_fXl3Meeuh:b3dxpct) ([raw file](https://github.com/m-lab/locate/blob/fc403555f89cd97e8bfdf6b2218f44ded46beaaf/cmd/heartbeat/health/endpoint-check_test.go#L45)):*
> ```Go
> 		},
> 		{
> 			name:    "error",
> ```

What is the error case? Please use a slightly more descriptive name.
___
*[`cmd/heartbeat/health/endpoint-check_test.go` line 53 at r3](https://reviewable.io/reviews/m-lab/locate/145#-N_p7eFNCC-YTLUbddOi:-N_p7eFNCC-YTLUbddOj:bo8arr) ([raw file](https://github.com/m-lab/locate/blob/fc403555f89cd97e8bfdf6b2218f44ded46beaaf/cmd/heartbeat/health/endpoint-check_test.go#L53)):*
> ```Go
> 	for _, tt := range tests {
> 		t.Run(tt.name, func(t *testing.T) {
> 			if !tt.wantErr {
> ```

Where is `tt.startSrv` used?

**Review by cristinaleonr — COMMENTED** [review]
Apologies for the multiple revisions! I double checked it now :sweat_smile:.

> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/145#-:-N_pPUuyD3SGpdjv-FTB:b3achac)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`cmd/heartbeat/health/endpoint-check_test.go` line 31 at r3](https://reviewable.io/reviews/m-lab/locate/145#-N_p7L3DAuDVUFvHiRiM:-N_pP_Mw6xZ66MUegw5C:b9koh7r) ([raw file](https://github.com/m-lab/locate/blob/fc403555f89cd97e8bfdf6b2218f44ded46beaaf/cmd/heartbeat/health/endpoint-check_test.go#L31)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This error case is labeled "timeout" -- but iiuc, an `http.Client` behavior with timeout = 0 is no timeout. What is this case testing?
</blockquote></details>

I separated this into a new test with a 1 second timeout.
___
*[`cmd/heartbeat/health/endpoint-check_test.go` line 45 at r3](https://reviewable.io/reviews/m-lab/locate/145#-N_p7t8zCZ_fXl3Meeug:-N_pQMjb-GVY9Jyu9qve:b-kpd9or) ([raw file](https://github.com/m-lab/locate/blob/fc403555f89cd97e8bfdf6b2218f44ded46beaaf/cmd/heartbeat/health/endpoint-check_test.go#L45)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What is the error case? Please use a slightly more descriptive name.
</blockquote></details>

The server is not running. Done.
___
*[`cmd/heartbeat/health/endpoint-check_test.go` line 53 at r3](https://reviewable.io/reviews/m-lab/locate/145#-N_p7eFNCC-YTLUbddOi:-N_pPvBO4s-LigUGLXgM:b-i63jzg) ([raw file](https://github.com/m-lab/locate/blob/fc403555f89cd97e8bfdf6b2218f44ded46beaaf/cmd/heartbeat/health/endpoint-check_test.go#L53)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Where is `tt.startSrv` used?
</blockquote></details>

Sorry, I removed it and just moved the test case to its own function.

I realized that and that's why I added the "Nvm, wait" comment :angel:.

**Review by stephen-soltesz — APPROVED** [review]
One suggested refinement if possible. :lgtm: 

> Reviewed 3 of 6 files at r1, 1 of 2 files at r2, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/145#-:-N_t0U7V5WrJBsP-g4eI:bfiibd3)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`cmd/heartbeat/health/endpoint-check_test.go` line 66 at r4](https://reviewable.io/reviews/m-lab/locate/145#-N_t-rwE5EwwfxhB-8th:-N_t-rwE5EwwfxhB-8ti:b-1xuhqn) ([raw file](https://github.com/m-lab/locate/blob/97614499c26ccb687e7caf607896df9e107ac952/cmd/heartbeat/health/endpoint-check_test.go#L66)):*
> ```Go
> 	got, err := hc.checkHealthEndpoint()
> 	if err == nil {
> 		t.Errorf("checkHealthEndpoint() error = %v, wantErr %s", err, "context deadline error")
> ```

Is it possible to add an affirmative `errors.Is` check for `context deadline error`? I see `context.DeadlineExceeded` -- this would be nice if possible. Not blocking if not.
___
*[`cmd/heartbeat/health/healthtest/healthtest.go` line 18 at r4](https://reviewable.io/reviews/m-lab/locate/145#-N_t0PCK2nj6uR-vpj2p:-N_t0PCK2nj6uR-vpj2q:b-8fx2ut) ([raw file](https://github.com/m-lab/locate/blob/97614499c26ccb687e7caf607896df9e107ac952/cmd/heartbeat/health/healthtest/healthtest.go#L18)):*
> ```Go
> }
> 
> func TestTimeoutServer(timeout time.Duration) *httptest.Server {
> ```

:+1:

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/145)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`cmd/heartbeat/health/endpoint-check_test.go` line 66 at r4](https://reviewable.io/reviews/m-lab/locate/145#-N_t-rwE5EwwfxhB-8th:-N_t4A1-DhKTzVjudmnA:bbh6hep) ([raw file](https://github.com/m-lab/locate/blob/97614499c26ccb687e7caf607896df9e107ac952/cmd/heartbeat/health/endpoint-check_test.go#L66)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Even though the error message is of the form ` Get "http://127.0.0.1:44235/health": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`, it must not specifically wrap that error since the `errors.Is` check returns false.
</blockquote></details>

Agh, hold on again, please.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/145)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`cmd/heartbeat/health/endpoint-check_test.go` line 66 at r4](https://reviewable.io/reviews/m-lab/locate/145#-N_t-rwE5EwwfxhB-8th:-N_t4Uko-7AyhrOiO7RU:b-c5amn1) ([raw file](https://github.com/m-lab/locate/blob/97614499c26ccb687e7caf607896df9e107ac952/cmd/heartbeat/health/endpoint-check_test.go#L66)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Agh, hold on again, please.
</blockquote></details>

Yep, my original statement above is right (I was double checking :angel:).

**Comment by cristinaleonr** [comment]
Related to https://github.com/m-lab/locate/issues/149.

**Pull request merged**
