### PR TITLE
Add Prometheus health signals to server selection

### PR DESCRIPTION
**Pull request by cristinaleonr**
This PR adds functionality to save the Prometheus health signals locally and in Memorystore. It uses those signals in its server selection algorithm.

Sample Memorystore entry including Prometheus field:
```
Registration
$471
{"City":"New York","CountryCode":"US","ContinentCode":"NA","Experiment":"ndt","Hostname":"ndt-mlab1-lga0t.mlab-sandbox.measurement-lab.org","Latitude":40.7667,"Longitude":-73.8667,"Machine":"mlab1","Metro":"lga","Project":"mlab-sandbox","Site":"lga0t","Type":"physical","Uplink":"10g","Services":{"ndt/ndt5":["ws://:3001/ndt_protocol","wss://:3010/ndt_protocol"],"ndt/ndt7":["ws:///ndt/v7/download","ws:///ndt/v7/upload","wss:///ndt/v7/download","wss:///ndt/v7/upload"]}}
$6
Health
$11
{"Score":1}
$10
Prometheus
$15
{"Health":true}**
```

Changes were tested by putting machines into maintenance (e.g., [mlab1-lax0t](https://github.com/m-lab/ops-tracker/issues/1684)) and verifying that they were excluded from the results while the machine was in maintenance.

Results for https://locate-dot-mlab-sandbox.appspot.com/v2beta2/nearest/ndt/ndt7?machine-type=virtual&api_key=$API_KEY when the machine is in maintenance:
```
{
  "results": [
    {
      "machine": "mlab2-chs0t.mlab-sandbox.measurement-lab.org",
      "location": {
        "city": "Charleston",
        "country": "US"
      },
      "urls": {
        "ws:///ndt/v7/download": "ws://ndt-mlab2-chs0t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjItY2hzMHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjY3NzcxMzk0LCJpc3MiOiJsb2NhdGUiLCJqdGkiOiI2YjFiMTFhZS1lMmUzLTRjMmMtYjU3Ny1lYWVhMWI0OGM3ZjAiLCJzdWIiOiJuZHQifQ.dAix2IOEgfUQGG3or2piGUNSOZH6IDZhBen4pXfyYF1H3hY1-humOmVFpRcQFGzeEmGa-jqgdqKTdBtGOUlADw",
        "ws:///ndt/v7/upload": "ws://ndt-mlab2-chs0t.mlab-sandbox.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjItY2hzMHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjY3NzcxMzk0LCJpc3MiOiJsb2NhdGUiLCJqdGkiOiI2YjFiMTFhZS1lMmUzLTRjMmMtYjU3Ny1lYWVhMWI0OGM3ZjAiLCJzdWIiOiJuZHQifQ.dAix2IOEgfUQGG3or2piGUNSOZH6IDZhBen4pXfyYF1H3hY1-humOmVFpRcQFGzeEmGa-jqgdqKTdBtGOUlADw",
        "wss:///ndt/v7/download": "wss://ndt-mlab2-chs0t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjItY2hzMHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjY3NzcxMzk0LCJpc3MiOiJsb2NhdGUiLCJqdGkiOiI2YjFiMTFhZS1lMmUzLTRjMmMtYjU3Ny1lYWVhMWI0OGM3ZjAiLCJzdWIiOiJuZHQifQ.dAix2IOEgfUQGG3or2piGUNSOZH6IDZhBen4pXfyYF1H3hY1-humOmVFpRcQFGzeEmGa-jqgdqKTdBtGOUlADw",
        "wss:///ndt/v7/upload": "wss://ndt-mlab2-chs0t.mlab-sandbox.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjItY2hzMHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjY3NzcxMzk0LCJpc3MiOiJsb2NhdGUiLCJqdGkiOiI2YjFiMTFhZS1lMmUzLTRjMmMtYjU3Ny1lYWVhMWI0OGM3ZjAiLCJzdWIiOiJuZHQifQ.dAix2IOEgfUQGG3or2piGUNSOZH6IDZhBen4pXfyYF1H3hY1-humOmVFpRcQFGzeEmGa-jqgdqKTdBtGOUlADw"
      }
    },
    {
      "machine": "mlab1-pdx0t.mlab-sandbox.measurement-lab.org",
      "location": {
        "city": "Portland",
        "country": "US"
      },
      "urls": {
        "ws:///ndt/v7/download": "ws://ndt-mlab1-pdx0t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtcGR4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjY3NzcxMzk0LCJpc3MiOiJsb2NhdGUiLCJqdGkiOiIxNzkzMWNlMS03Y2UxLTQ2ZDktODcxMy1iM2FmOGQ5Yzg4YTEiLCJzdWIiOiJuZHQifQ.L4EoLOqeYwgLzCs0bd2PhYR7XtAltLy5_4FHFBZ6zNHQYZzh9tCLG2UWJ3cf4ArULDBC5tdzn4AwAMh9ZcnTCg",
        "ws:///ndt/v7/upload": "ws://ndt-mlab1-pdx0t.mlab-sandbox.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtcGR4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjY3NzcxMzk0LCJpc3MiOiJsb2NhdGUiLCJqdGkiOiIxNzkzMWNlMS03Y2UxLTQ2ZDktODcxMy1iM2FmOGQ5Yzg4YTEiLCJzdWIiOiJuZHQifQ.L4EoLOqeYwgLzCs0bd2PhYR7XtAltLy5_4FHFBZ6zNHQYZzh9tCLG2UWJ3cf4ArULDBC5tdzn4AwAMh9ZcnTCg",
        "wss:///ndt/v7/download": "wss://ndt-mlab1-pdx0t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtcGR4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjY3NzcxMzk0LCJpc3MiOiJsb2NhdGUiLCJqdGkiOiIxNzkzMWNlMS03Y2UxLTQ2ZDktODcxMy1iM2FmOGQ5Yzg4YTEiLCJzdWIiOiJuZHQifQ.L4EoLOqeYwgLzCs0bd2PhYR7XtAltLy5_4FHFBZ6zNHQYZzh9tCLG2UWJ3cf4ArULDBC5tdzn4AwAMh9ZcnTCg",
        "wss:///ndt/v7/upload": "wss://ndt-mlab1-pdx0t.mlab-sandbox.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtcGR4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjY3NzcxMzk0LCJpc3MiOiJsb2NhdGUiLCJqdGkiOiIxNzkzMWNlMS03Y2UxLTQ2ZDktODcxMy1iM2FmOGQ5Yzg4YTEiLCJzdWIiOiJuZHQifQ.L4EoLOqeYwgLzCs0bd2PhYR7XtAltLy5_4FHFBZ6zNHQYZzh9tCLG2UWJ3cf4ArULDBC5tdzn4AwAMh9ZcnTCg"
      }
    }
  ]
}
```

And when it's out of maintenance:
```
{
  "results": [
    {
      "machine": "mlab1-chs0t.mlab-sandbox.measurement-lab.org",
      "location": {
        "city": "Charleston",
        "country": "US"
      },
      "urls": {
        "ws:///ndt/v7/download": "ws://ndt-mlab1-chs0t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtY2hzMHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjY3NzcyMzY2LCJpc3MiOiJsb2NhdGUiLCJqdGkiOiI5NDFiNWU3NS1iZjMzLTQyMjgtYjM4OC1lNmM3Mzg3OTIyZGYiLCJzdWIiOiJuZHQifQ.m2ow-fonMXXY6x_qc7QjZ7bK5DuUSSFJImCNZjW0Y7nS355LId9__0fC0QZbuO1ky6DGvkjWxZGg-OUsdHzCCQ",
        "ws:///ndt/v7/upload": "ws://ndt-mlab1-chs0t.mlab-sandbox.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtY2hzMHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjY3NzcyMzY2LCJpc3MiOiJsb2NhdGUiLCJqdGkiOiI5NDFiNWU3NS1iZjMzLTQyMjgtYjM4OC1lNmM3Mzg3OTIyZGYiLCJzdWIiOiJuZHQifQ.m2ow-fonMXXY6x_qc7QjZ7bK5DuUSSFJImCNZjW0Y7nS355LId9__0fC0QZbuO1ky6DGvkjWxZGg-OUsdHzCCQ",
        "wss:///ndt/v7/download": "wss://ndt-mlab1-chs0t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtY2hzMHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjY3NzcyMzY2LCJpc3MiOiJsb2NhdGUiLCJqdGkiOiI5NDFiNWU3NS1iZjMzLTQyMjgtYjM4OC1lNmM3Mzg3OTIyZGYiLCJzdWIiOiJuZHQifQ.m2ow-fonMXXY6x_qc7QjZ7bK5DuUSSFJImCNZjW0Y7nS355LId9__0fC0QZbuO1ky6DGvkjWxZGg-OUsdHzCCQ",
        "wss:///ndt/v7/upload": "wss://ndt-mlab1-chs0t.mlab-sandbox.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtY2hzMHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjY3NzcyMzY2LCJpc3MiOiJsb2NhdGUiLCJqdGkiOiI5NDFiNWU3NS1iZjMzLTQyMjgtYjM4OC1lNmM3Mzg3OTIyZGYiLCJzdWIiOiJuZHQifQ.m2ow-fonMXXY6x_qc7QjZ7bK5DuUSSFJImCNZjW0Y7nS355LId9__0fC0QZbuO1ky6DGvkjWxZGg-OUsdHzCCQ"
      }
    },
    {
      "machine": "mlab1-pdx0t.mlab-sandbox.measurement-lab.org",
      "location": {
        "city": "Portland",
        "country": "US"
      },
      "urls": {
        "ws:///ndt/v7/download": "ws://ndt-mlab1-pdx0t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtcGR4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjY3NzcyMzY2LCJpc3MiOiJsb2NhdGUiLCJqdGkiOiI3MjA2NjY0OS1iNjcwLTQyZDctYmNiZi04N2JiMTFhY2FhZDkiLCJzdWIiOiJuZHQifQ.bUflcwBKdiCRQK5n6LU2t6giN72suwVlrhcJznJ7qsxp21OuBAwx5UowhiFZFI-VTE2yTrPXy-AYkbdl36iiBQ",
        "ws:///ndt/v7/upload": "ws://ndt-mlab1-pdx0t.mlab-sandbox.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtcGR4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjY3NzcyMzY2LCJpc3MiOiJsb2NhdGUiLCJqdGkiOiI3MjA2NjY0OS1iNjcwLTQyZDctYmNiZi04N2JiMTFhY2FhZDkiLCJzdWIiOiJuZHQifQ.bUflcwBKdiCRQK5n6LU2t6giN72suwVlrhcJznJ7qsxp21OuBAwx5UowhiFZFI-VTE2yTrPXy-AYkbdl36iiBQ",
        "wss:///ndt/v7/download": "wss://ndt-mlab1-pdx0t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtcGR4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjY3NzcyMzY2LCJpc3MiOiJsb2NhdGUiLCJqdGkiOiI3MjA2NjY0OS1iNjcwLTQyZDctYmNiZi04N2JiMTFhY2FhZDkiLCJzdWIiOiJuZHQifQ.bUflcwBKdiCRQK5n6LU2t6giN72suwVlrhcJznJ7qsxp21OuBAwx5UowhiFZFI-VTE2yTrPXy-AYkbdl36iiBQ",
        "wss:///ndt/v7/upload": "wss://ndt-mlab1-pdx0t.mlab-sandbox.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtcGR4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjY3NzcyMzY2LCJpc3MiOiJsb2NhdGUiLCJqdGkiOiI3MjA2NjY0OS1iNjcwLTQyZDctYmNiZi04N2JiMTFhY2FhZDkiLCJzdWIiOiJuZHQifQ.bUflcwBKdiCRQK5n6LU2t6giN72suwVlrhcJznJ7qsxp21OuBAwx5UowhiFZFI-VTE2yTrPXy-AYkbdl36iiBQ"
      }
    },
    {
      "machine": "mlab1-lax0t.mlab-sandbox.measurement-lab.org",
      "location": {
        "city": "Los Angeles",
        "country": "US"
      },
      "urls": {
        "ws:///ndt/v7/download": "ws://ndt-mlab1-lax0t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtbGF4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjY3NzcyMzY2LCJpc3MiOiJsb2NhdGUiLCJqdGkiOiIwNmNkNTIwYi1jYmI0LTRlMGEtOWMyYy0zMTZmODllOTg3NTgiLCJzdWIiOiJuZHQifQ.PoTK0xDXrCvpiWerORODrNJ1oXBDusw-x1rHDSrE1xgqBksgNyojthvkMBnWXKnGIZb-x8hEUN9VLnaT40F6Cg",
        "ws:///ndt/v7/upload": "ws://ndt-mlab1-lax0t.mlab-sandbox.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtbGF4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjY3NzcyMzY2LCJpc3MiOiJsb2NhdGUiLCJqdGkiOiIwNmNkNTIwYi1jYmI0LTRlMGEtOWMyYy0zMTZmODllOTg3NTgiLCJzdWIiOiJuZHQifQ.PoTK0xDXrCvpiWerORODrNJ1oXBDusw-x1rHDSrE1xgqBksgNyojthvkMBnWXKnGIZb-x8hEUN9VLnaT40F6Cg",
        "wss:///ndt/v7/download": "wss://ndt-mlab1-lax0t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtbGF4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjY3NzcyMzY2LCJpc3MiOiJsb2NhdGUiLCJqdGkiOiIwNmNkNTIwYi1jYmI0LTRlMGEtOWMyYy0zMTZmODllOTg3NTgiLCJzdWIiOiJuZHQifQ.PoTK0xDXrCvpiWerORODrNJ1oXBDusw-x1rHDSrE1xgqBksgNyojthvkMBnWXKnGIZb-x8hEUN9VLnaT40F6Cg",
        "wss:///ndt/v7/upload": "wss://ndt-mlab1-lax0t.mlab-sandbox.measurement-lab.org/ndt/v7/upload?access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImxvY2F0ZV8yMDIwMDQwOSJ9.eyJhdWQiOlsibWxhYjEtbGF4MHQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNjY3NzcyMzY2LCJpc3MiOiJsb2NhdGUiLCJqdGkiOiIwNmNkNTIwYi1jYmI0LTRlMGEtOWMyYy0zMTZmODllOTg3NTgiLCJzdWIiOiJuZHQifQ.PoTK0xDXrCvpiWerORODrNJ1oXBDusw-x1rHDSrE1xgqBksgNyojthvkMBnWXKnGIZb-x8hEUN9VLnaT40F6Cg"
      }
    }
  ]
}
```

This change is [Reviewable](https://reviewable.io/reviews/m-lab/locate/87)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
Small requests for clarity. 

> Reviewed 9 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/87#-:-NGHct1-EQRRk7yCgKAs:b-dkg3m7)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`heartbeat/heartbeat.go` line 85 at r1](https://reviewable.io/reviews/m-lab/locate/87#-NGHbNWx9Uol4Q0Zy7M8:-NGHbNWx9Uol4Q0Zy7M9:b-ij97vo) ([raw file](https://github.com/m-lab/locate/blob/4b8ea250c067ab623ecabf6f3316536eb65ef35a/heartbeat/heartbeat.go#L85)):*
> ```Go
> 
> // UpdatePrometheus updates the v2.Prometheus field for the instances.
> func (h *heartbeatStatusTracker) UpdatePrometheus(hostnames, machines map[string]bool) error {
> ```

I'm finding this set of method names confusing this morning. Can they be simplified or clarified?

UpdatePrometheus
getPrometheusMessage
updatePrometheusInstance
updatePrometheusLocally
___
*[`heartbeat/heartbeat.go` line 188 at r1](https://reviewable.io/reviews/m-lab/locate/87#-NGHZaSD4P9Hlisiw-kx:-NGHZaSD4P9Hlisiw-ky:b-r7ub9s) ([raw file](https://github.com/m-lab/locate/blob/4b8ea250c067ab623ecabf6f3316536eb65ef35a/heartbeat/heartbeat.go#L188)):*
> ```Go
> 	// Create Prometheus health message.
> 	if hostFound || machineFound {
> 		health := (!hostFound || hostHealthy) && (!machineFound || machineHealthy)
> ```

Making sure I understand the intent here:

* if prometheus does not know about one of host or machine, treat it as healthy.
* if prometheus does not know about either, return unknown.

is 'unknown' treated the same way downstream by the caller as 'healthy'?

a short comment for the intent and the distinction of these cases would be welcome.
___
*[`heartbeat/heartbeat_test.go` line 206 at r1](https://reviewable.io/reviews/m-lab/locate/87#-NGHbCIPATj7fBs1iExG:-NGHbCIPATj7fBs1iExH:bb6mt9b) ([raw file](https://github.com/m-lab/locate/blob/4b8ea250c067ab623ecabf6f3316536eb65ef35a/heartbeat/heartbeat_test.go#L206)):*
> ```Go
> }
> 
> func TestGetPrometheusMessage(t *testing.T) {
> ```

:+1:

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/87)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`heartbeat/heartbeat.go` line 85 at r1](https://reviewable.io/reviews/m-lab/locate/87#-NGHbNWx9Uol4Q0Zy7M8:-NGHiF15-p00B3uwjPpk:bgz6vzz) ([raw file](https://github.com/m-lab/locate/blob/4b8ea250c067ab623ecabf6f3316536eb65ef35a/heartbeat/heartbeat.go#L85)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I'm finding this set of method names confusing this morning. Can they be simplified or clarified?

UpdatePrometheus
getPrometheusMessage
updatePrometheusInstance
updatePrometheusLocally


</blockquote></details>

I tried to refactor this so many times when I was making the PR. I think it had the opposite effect :sweat_smile:.

I incorporated `updatePrometheusLocally` into `updatePrometheusInstance` and renamed `getPrometheusMessage` to `constructPrometheusMessage`. I also updated some comments. 

Is that more clear?
___
*[`heartbeat/heartbeat.go` line 188 at r1](https://reviewable.io/reviews/m-lab/locate/87#-NGHZaSD4P9Hlisiw-kx:-NGHjF7G6X3LyLCdzKHG:bbcvglq) ([raw file](https://github.com/m-lab/locate/blob/4b8ea250c067ab623ecabf6f3316536eb65ef35a/heartbeat/heartbeat.go#L188)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Making sure I understand the intent here:

* if prometheus does not know about one of host or machine, treat it as healthy.
* if prometheus does not know about either, return unknown.

is 'unknown' treated the same way downstream by the caller as 'healthy'?

a short comment for the intent and the distinction of these cases would be welcome.
</blockquote></details>

If by 'unknown' you mean `nil`, then yes, that is the intended logic. I added some comments. 

And yes, if the Prometheus field is `nil`, it is treated the same way as a healthy server.

**Review by stephen-soltesz — APPROVED** [review]
Thank you. One more suggestion, then :lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/87#-:-NGHrVvV2r8ifrUWQv8p:bwxh0m4)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`heartbeat/heartbeat.go` line 85 at r1](https://reviewable.io/reviews/m-lab/locate/87#-NGHbNWx9Uol4Q0Zy7M8:-NGHqi6cB3ST3G9pC5Gq:boqcug5) ([raw file](https://github.com/m-lab/locate/blob/4b8ea250c067ab623ecabf6f3316536eb65ef35a/heartbeat/heartbeat.go#L85)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

I tried to refactor this so many times when I was making the PR. I think it had the opposite effect :sweat_smile:.

I incorporated `updatePrometheusLocally` into `updatePrometheusInstance` and renamed `getPrometheusMessage` to `constructPrometheusMessage`. I also updated some comments. 

Is that more clear?
</blockquote></details>

Thank you. Naming things is hard.

I like 'construct'.

Are `constructPrometheusMessage` and `updatePrometheusInstance` operating on the same type?

What do you think of: `updatePrometheusMessage`

The logic of the loop would read then as "create a message for this instance, update the message for this instance".

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/87)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`heartbeat/heartbeat.go` line 85 at r1](https://reviewable.io/reviews/m-lab/locate/87#-NGHbNWx9Uol4Q0Zy7M8:-NGHxuU64SUVvJNNvnI_:bctpdbz) ([raw file](https://github.com/m-lab/locate/blob/4b8ea250c067ab623ecabf6f3316536eb65ef35a/heartbeat/heartbeat.go#L85)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Thank you. Naming things is hard.

I like 'construct'.

Are `constructPrometheusMessage` and `updatePrometheusInstance` operating on the same type?

What do you think of: `updatePrometheusMessage`

The logic of the loop would read then as "create a message for this instance, update the message for this instance".
</blockquote></details>

Makes sense. Done!

**Pull request merged**
