### PR TITLE
Implement port probing for HBS

### PR DESCRIPTION
**Pull request by cristinaleonr**
This PR adds a new `HealthChecker`, which performs all the HBS local health checks and combines them into a score. The HBS then sends that score to the Locate.

It also adds a `PortChecker`, which checks whether the ports that the instance should be listening on are reachable. The `HealthChecker` uses this information to produce its health score.

Tested by making a test docker image and updating the image version in k8s-support in sandbox.

This change is [Reviewable](https://reviewable.io/reviews/m-lab/locate/78)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/78)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`cmd/heartbeat/port-checker.go` line 34 at r1](https://reviewable.io/reviews/m-lab/locate/78#-N8ZWr6B4MDlY0mP6liN:-N8ZWr6B4MDlY0mP6liO:b77ri1r) ([raw file](https://github.com/m-lab/locate/blob/d289999d8ce183f71b472df99d339412e244bf9d/cmd/heartbeat/port-checker.go#L34)):*
> ```Go
> 		conn, err := net.DialTimeout("tcp", p, time.Second)
> 		if err != nil {
> 			log.Printf("Failed to reach port %s", p)
> ```

Maybe this could be captured by a metric.

**Review by stephen-soltesz — COMMENTED** [review]
small comments and thoughts.

> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/78#-:-N8_ORIf4I72QKLNZ_XY:beftwfx)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`cmd/heartbeat/health-checker.go` line 9 at r2](https://reviewable.io/reviews/m-lab/locate/78#-N8_O-Jr9nED-l4PqRIN:-N8_O-Jr9nED-l4PqRIO:bmdpzqg) ([raw file](https://github.com/m-lab/locate/blob/76df1dbe6cdec68a149a1c34bde2d0b5ce68fd67/cmd/heartbeat/health-checker.go#L9)):*
> ```Go
> 
> // NewHealthChecker creates a new HealthChecker.
> func NewHealthChecker(pc PortChecker) *HealthChecker {
> ```

I wondered whether we needed the HealthChecker and PortChecker -- I imagine this type will incorporate more information/checkers in the future?
___
*[`cmd/heartbeat/main.go` line 56 at r2](https://reviewable.io/reviews/m-lab/locate/78#-N8_NkUZ31KbvzO42H15:-N8_NkU_376r83zzIuy2:b8ewydn) ([raw file](https://github.com/m-lab/locate/blob/76df1dbe6cdec68a149a1c34bde2d0b5ce68fd67/cmd/heartbeat/main.go#L56)):*
> ```Go
> 
> 	pc := NewPortChecker(s)
> 	hc := NewHealthChecker(*pc)
> ```

Can this function accept a pointer? The dereference looks out of place.
___
*[`cmd/heartbeat/port-checker.go` line 1 at r2](https://reviewable.io/reviews/m-lab/locate/78#-N8_JL3JA9XnK7-9wnER:-N8_JL3JA9XnK7-9wnES:bd7emth) ([raw file](https://github.com/m-lab/locate/blob/76df1dbe6cdec68a149a1c34bde2d0b5ce68fd67/cmd/heartbeat/port-checker.go#L1)):*
> ```Go
> package main
> ```

There's a lot going on in `main` these days :)
___
*[`cmd/heartbeat/port-checker.go` line 31 at r2](https://reviewable.io/reviews/m-lab/locate/78#-N8_L3jeD-TyQ2cFHmuj:-N8_L3jeD-TyQ2cFHmuk:b-6vb3gx) ([raw file](https://github.com/m-lab/locate/blob/76df1dbe6cdec68a149a1c34bde2d0b5ce68fd67/cmd/heartbeat/port-checker.go#L31)):*
> ```Go
> // otherwise.
> // When dialing tcp networks, if the host is empty, the "net" package
> // uses the local system. This implementation only passes in the port
> ```

Hmm, I'm not confident "local system" guarantees "localhost"... some of our services specify the private IP https://github.com/m-lab/k8s-support/blob/master/k8s/daemonsets/templates.jsonnet (I know this is not the initial or primary target of the service ports) .. would specifying only port with `net.Dial` connect to these services, or only services listening on 0.0.0.0?

 Just thinking out loud: considering this question also made me wonder whether the sidecar service health should be considered a factor in the whole pod service health. This seems attractive, e.g. if the disk was full or cpu exhausted from load, even if NDT's ports were open.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/78)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`cmd/heartbeat/main.go` line 56 at r2](https://reviewable.io/reviews/m-lab/locate/78#-N8_NkUZ31KbvzO42H15:-N8_pRsyEPGpl7EFwo48:b-896fix) ([raw file](https://github.com/m-lab/locate/blob/76df1dbe6cdec68a149a1c34bde2d0b5ce68fd67/cmd/heartbeat/main.go#L56)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Can this function accept a pointer? The dereference looks out of place.
</blockquote></details>

Done.
___
*[`cmd/heartbeat/health-checker.go` line 9 at r2](https://reviewable.io/reviews/m-lab/locate/78#-N8_O-Jr9nED-l4PqRIN:-N8_wz-fBLWg0wnboD93:b48iv83) ([raw file](https://github.com/m-lab/locate/blob/76df1dbe6cdec68a149a1c34bde2d0b5ce68fd67/cmd/heartbeat/health-checker.go#L9)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I wondered whether we needed the HealthChecker and PortChecker -- I imagine this type will incorporate more information/checkers in the future?
</blockquote></details>

Yes, it will incorporate more information (.e.g, the output of the /health endpoint).
___
*[`cmd/heartbeat/port-checker.go` line 1 at r2](https://reviewable.io/reviews/m-lab/locate/78#-N8_JL3JA9XnK7-9wnER:-N8_pT8N2RkP68E8klQ5:b-fv8ugs) ([raw file](https://github.com/m-lab/locate/blob/76df1dbe6cdec68a149a1c34bde2d0b5ce68fd67/cmd/heartbeat/port-checker.go#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

There's a lot going on in `main` these days :)
</blockquote></details>

Yes, I thought about that. Last time we tried to add a new package with Heartbeat logic, you said we should [move it to cmd/heartbeat](https://reviewable.io/reviews/m-lab/locate/68#-N4Xbq0Z4p_y4I1BNKnO) because that would be the only package that would use it (as is the case here), so that's why I put it here.

I have moved it to its own package now.
___
*[`cmd/heartbeat/port-checker.go` line 31 at r2](https://reviewable.io/reviews/m-lab/locate/78#-N8_L3jeD-TyQ2cFHmuj:-N8_qT-D5WAd4f1VvrtQ:b-76vtdm) ([raw file](https://github.com/m-lab/locate/blob/76df1dbe6cdec68a149a1c34bde2d0b5ce68fd67/cmd/heartbeat/port-checker.go#L31)):*
I have added "localhost" to the address to make sure it's guaranteed. 

I tested connecting to another service (i.e., pusher) over localhost (i.e., localhost:9995) but failed to connect. Is there some other service/port that I can test that should be reachable?


>Just thinking out loud: considering this question also made me wonder whether the sidecar service health should be considered a factor in the whole pod service health. 

Which sidecar service are you referring to?

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/78#-:-N8a3M8r2wahJjNQAoh4:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`cmd/heartbeat/port-checker.go` line 31 at r2](https://reviewable.io/reviews/m-lab/locate/78#-N8_L3jeD-TyQ2cFHmuj:-N8a1oLh4j7zj4Mi0vx3:b-1whzcj) ([raw file](https://github.com/m-lab/locate/blob/76df1dbe6cdec68a149a1c34bde2d0b5ce68fd67/cmd/heartbeat/port-checker.go#L31)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

I have added "localhost" to the address to make sure it's guaranteed. 

I tested connecting to another service (i.e., pusher) over localhost (i.e., localhost:9995) but failed to connect. Is there some other service/port that I can test that should be reachable?


>Just thinking out loud: considering this question also made me wonder whether the sidecar service health should be considered a factor in the whole pod service health. 

Which sidecar service are you referring to?

</blockquote></details>

Thank you for adding "localhost" -- that guarantees it.

Hmm, most nodes/services won't have pusher listening on localhost, but the private network IP - https://github.com/m-lab/k8s-support/blob/master/k8s/daemonsets/templates.jsonnet#L265 - this was to ensure that it could be scraped by prometheus and not exposed on the public IPs.

I was thinking about sidecars like pusher, packet-headers, tcp-info, any that we regard as "core" and if they were unhealthy for some reason, would we want to keep collecting measurement traffic? Maybe they could each have /health endpoints.. but this feels a little too speculative for now.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/78)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`cmd/heartbeat/port-checker.go` line 31 at r2](https://reviewable.io/reviews/m-lab/locate/78#-N8_L3jeD-TyQ2cFHmuj:-N8a3pSn8U0utd7tCcLm:b7zdpht) ([raw file](https://github.com/m-lab/locate/blob/76df1dbe6cdec68a149a1c34bde2d0b5ce68fd67/cmd/heartbeat/port-checker.go#L31)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Thank you for adding "localhost" -- that guarantees it.

Hmm, most nodes/services won't have pusher listening on localhost, but the private network IP - https://github.com/m-lab/k8s-support/blob/master/k8s/daemonsets/templates.jsonnet#L265 - this was to ensure that it could be scraped by prometheus and not exposed on the public IPs.

I was thinking about sidecars like pusher, packet-headers, tcp-info, any that we regard as "core" and if they were unhealthy for some reason, would we want to keep collecting measurement traffic? Maybe they could each have /health endpoints.. but this feels a little too speculative for now.
</blockquote></details>

I agree that it's a little too speculative at the moment, and it's the reason why I asked which sidecar you meant. 

It makes sense to me in theory. We would need to discuss further to see which specific signals would be useful.

**Pull request merged**
