### PR TITLE
Add Ready and Live request handlers

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds two new handlers to the Locate v2 for liveness and readiness checks in the App Engine configuration.

With this change:
* /v2/live - unconditionally returns success. This resource tests the minimal live condition for the server.
* /v2/ready - returns success only if the Memorystore import has occurred successfully recently.

These resources are now referenced in new `readiness_check` and `liveness_check` settings in the App Engine app.yaml configuration.

These changes are expected to address https://github.com/m-lab/locate/issues/114

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/locate/118)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
Thanks for this!

As discussed, I believe this is helpful, but I don't think it will address #114.

> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/118#-:-NOqFQi95N_WLF99sImr:bppc74a)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`cloudbuild/app.yaml.template` line 24 at r1](https://reviewable.io/reviews/m-lab/locate/118#-NOqBozI6N1l1RqtjiUP:-NOqBozI6N1l1RqtjiUQ:b-10bdat) ([raw file](https://github.com/m-lab/locate/blob/bf3c873fb130b890a82e83bc6aead31cdf6923da/cloudbuild/app.yaml.template#L24)):*
> ```
> 
> liveness_check:
>   path: "/v2/live"
> ```

What is the difference between this and the liveness check App Engine does natively?
___
*[`cloudbuild/app.yaml.template` line 29 at r1](https://reviewable.io/reviews/m-lab/locate/118#-NOqCmlRAJA6VYCvuzJK:-NOqCmlRAJA6VYCvuzJL:bc6u3xb) ([raw file](https://github.com/m-lab/locate/blob/bf3c873fb130b890a82e83bc6aead31cdf6923da/cloudbuild/app.yaml.template#L29)):*
> ```
> readiness_check:
>   path: "/v2/ready"
>   check_interval_sec: 10  # Note: this frequency is twice as often as we expect the memorystore import to succeed.
> ```

I'm not sure I understand the comment. Memorystore is called every 10 seconds.
___
*[`cloudbuild/app.yaml.template` line 30 at r1](https://reviewable.io/reviews/m-lab/locate/118#-NOqCdAQ7qtWwrYsbPmP:-NOqCdAQ7qtWwrYsbPmQ:b4c9lyr) ([raw file](https://github.com/m-lab/locate/blob/bf3c873fb130b890a82e83bc6aead31cdf6923da/cloudbuild/app.yaml.template#L30)):*
> ```
>   path: "/v2/ready"
>   check_interval_sec: 10  # Note: this frequency is twice as often as we expect the memorystore import to succeed.
>   app_start_timeout_sec: 600
> ```

:thumbsup: 
___
*[`handler/handler_test.go` line 466 at r1](https://reviewable.io/reviews/m-lab/locate/118#-NOqDVCKB_9VWNiohdTu:-NOqDVCKB_9VWNiohdTv:bfjz2vx) ([raw file](https://github.com/m-lab/locate/blob/bf3c873fb130b890a82e83bc6aead31cdf6923da/handler/handler_test.go#L466)):*
> ```Go
> 			rtx.Must(err, "failed to issue request")
> 			if resp.StatusCode != http.StatusOK {
> 				t.Errorf("Ready() wrong status; got %d; want %d", resp.StatusCode, http.StatusOK)
> ```

Should this say "Live()"?
___
*[`heartbeat/heartbeattest/heartbeattest.go` line 78 at r1](https://reviewable.io/reviews/m-lab/locate/118#-NOqF4hh3D2elWyzMMrP:-NOqF4hh3D2elWyzMMrQ:bv46hqk) ([raw file](https://github.com/m-lab/locate/blob/bf3c873fb130b890a82e83bc6aead31cdf6923da/heartbeat/heartbeattest/heartbeattest.go#L78)):*
> ```Go
> }
> 
> // Ready always return true.
> ```

returns*
___
*[`heartbeat/heartbeattest/heartbeattest.go` line 80 at r1](https://reviewable.io/reviews/m-lab/locate/118#-NOqEcc34vhXlz5HFJpA:-NOqEcc34vhXlz5HFJpB:b-pud4y3) ([raw file](https://github.com/m-lab/locate/blob/bf3c873fb130b890a82e83bc6aead31cdf6923da/heartbeat/heartbeattest/heartbeattest.go#L80)):*
> ```Go
> // Ready always return true.
> func (t *FakeStatusTracker) Ready() bool {
> 	return t.Err == nil
> ```

Shouldn't this be `return true`?

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/118)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`cloudbuild/app.yaml.template` line 24 at r1](https://reviewable.io/reviews/m-lab/locate/118#-NOqBozI6N1l1RqtjiUP:-NOqGlmuAQxScqGvS9bk:b7jcf56) ([raw file](https://github.com/m-lab/locate/blob/bf3c873fb130b890a82e83bc6aead31cdf6923da/cloudbuild/app.yaml.template#L24)):*
I based this on the description here: https://cloud.google.com/appengine/docs/flexible/reference/app-yaml?tab=go#liveness_checks

> By default, HTTP requests from health checks are not forwarded to your application container. If you want to extend health checks to your application, then specify a path for liveness checks or readiness checks.

I'm not sure what it's checking "by default" if it doesn't reach the application container, but this setting makes it explicit that the liveness check is "end to end" from the system that monitors liveness and our application container.

For my part, I think think this is in the category of "explicit is better than implicit".

Even without the heartbeat connection, in the back of my head, I suspect that the default app engine behavior was responsible for the deployment 5xx errors a few weeks ago. So, I'm hopeful this could help address that type of failure case also.
___
*[`cloudbuild/app.yaml.template` line 29 at r1](https://reviewable.io/reviews/m-lab/locate/118#-NOqCmlRAJA6VYCvuzJK:-NOqHIoy-3wPXBg29BDy:bn3ropl) ([raw file](https://github.com/m-lab/locate/blob/bf3c873fb130b890a82e83bc6aead31cdf6923da/cloudbuild/app.yaml.template#L29)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

I'm not sure I understand the comment. Memorystore is called every 10 seconds.
</blockquote></details>

I've rephrased. I'm trying to convey that this check interval depends on the threshold set in `heartbeat.go:Ready()`.

Today, that threshold is `2*static.MemorystoreExportPeriod`. (this value is arbitrary, but check_interval_sec's dependency on it is not).
___
*[`handler/handler_test.go` line 466 at r1](https://reviewable.io/reviews/m-lab/locate/118#-NOqDVCKB_9VWNiohdTu:-NOqHo3t102bL9suLoVy:bdpndgn) ([raw file](https://github.com/m-lab/locate/blob/bf3c873fb130b890a82e83bc6aead31cdf6923da/handler/handler_test.go#L466)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Should this say "Live()"?
</blockquote></details>

Yes, thank you. Done.
___
*[`heartbeat/heartbeattest/heartbeattest.go` line 78 at r1](https://reviewable.io/reviews/m-lab/locate/118#-NOqF4hh3D2elWyzMMrP:-NOqI1iUCrsZBECJBpwg:b-896fix) ([raw file](https://github.com/m-lab/locate/blob/bf3c873fb130b890a82e83bc6aead31cdf6923da/heartbeat/heartbeattest/heartbeattest.go#L78)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

returns*
</blockquote></details>

Done.
___
*[`heartbeat/heartbeattest/heartbeattest.go` line 80 at r1](https://reviewable.io/reviews/m-lab/locate/118#-NOqEcc34vhXlz5HFJpA:-NOqI1vL60uJtA3BlZEJ:b-qw6awi) ([raw file](https://github.com/m-lab/locate/blob/bf3c873fb130b890a82e83bc6aead31cdf6923da/heartbeat/heartbeattest/heartbeattest.go#L80)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Shouldn't this be `return true`?
</blockquote></details>

Updated docstring. I needed to inject a "not ready" failure too.

**Review by cristinaleonr — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/118#-:-NOtuN7nD7LkbT0ZvGMD:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

**Comment by stephen-soltesz** [comment]
Thank you!

**Pull request merged**
