### PR TITLE
Only write health/prometheus updates to Memorystore if key already exists

### PR DESCRIPTION
**Pull request by cristinaleonr**
This PR adds functionality to only write Health/Prometheus updates to Memorystore if the key already exists (i.e., the instance has been registered). If the entry does not already exist, an error will be returned.

During peak load events, some of the Memorystore entries are expiring. Because we were not checking whether the entry already existed when writing health/prometheus updates, the writes were succeeding and no errors were being reported.

Tested the changes in sandbox by deleting a key in Memorystore and checking that it disappeared and then re-appeared (with the Registration) in a few seconds.

```
HGETALL ndt-mlab4-lga0t.mlab-sandbox.measurement-lab.org
*6
$12
Registration
$487
{"City":"New York","CountryCode":"US","ContinentCode":"NA","Experiment":"ndt","Hostname":"ndt-mlab4-lga0t.mlab-sandbox.measurement-lab.org","Latitude":40.7667,"Longitude":-73.8667,"Machine":"mlab4","Metro":"lga","Project":"mlab-sandbox","Probability":1,"Site":"lga0t","Type":"physical","Uplink":"10g","Services":{"ndt/ndt5":["ws://:3001/ndt_protocol","wss://:3010/ndt_protocol"],"ndt/ndt7":["ws:///ndt/v7/download","ws:///ndt/v7/upload","wss:///ndt/v7/download","wss:///ndt/v7/upload"]}}
$6
Health
$11
{"Score":1}
$10
Prometheus
$15
{"Health":true}

DEL ndt-mlab4-lga0t.mlab-sandbox.measurement-lab.org
:1

HGETALL ndt-mlab4-lga0t.mlab-sandbox.measurement-lab.org
*0

HGETALL ndt-mlab4-lga0t.mlab-sandbox.measurement-lab.org
*6
$12
Registration
$487
{"City":"New York","CountryCode":"US","ContinentCode":"NA","Experiment":"ndt","Hostname":"ndt-mlab4-lga0t.mlab-sandbox.measurement-lab.org","Latitude":40.7667,"Longitude":-73.8667,"Machine":"mlab4","Metro":"lga","Project":"mlab-sandbox","Probability":1,"Site":"lga0t","Type":"physical","Uplink":"10g","Services":{"ndt/ndt5":["ws://:3001/ndt_protocol","wss://:3010/ndt_protocol"],"ndt/ndt7":["ws:///ndt/v7/download","ws:///ndt/v7/upload","wss:///ndt/v7/download","wss:///ndt/v7/upload"]}}
$6
Health
$11
{"Score":1}
$10
Prometheus
$15
{"Health":true}
```

Part of https://github.com/m-lab/locate/issues/149.

This change is [Reviewable](https://reviewable.io/reviews/m-lab/locate/154)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
Thank you for this. I've added some suggestions, clarifying questions and thoughts for how to evaluate this in context.

> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/154#-:-Nb1Q7JE2NblNeI6tPnC:b4zp7ua)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`heartbeat/heartbeat.go` line 169 at r1](https://reviewable.io/reviews/m-lab/locate/154#-Nb1PbpLDzCkjuyojrLj:-Nb1PbpLDzCkjuyojrLk:bpcc5lr) ([raw file](https://github.com/m-lab/locate/blob/e0d795680267a30783e95608a385783cec76e9c8/heartbeat/heartbeat.go#L169)):*
> ```Go
> func (h *heartbeatStatusTracker) updatePrometheusMessage(instance v2.HeartbeatMessage, pm *v2.Prometheus) error {
> 	hostname := instance.Registration.Hostname
> 	opts := &memorystore.PutOptions{Exists: true, Expire: false}
> ```

Just clarifying: prometheus status does not expire? B/c the expiration time is only long enough for heartbeats?

Also clarifying, are there stale prometheus records in redis for retired nodes?
___
*[`memorystore/client.go` line 13 at r1](https://reviewable.io/reviews/m-lab/locate/154#-Nb1IOwfAyEJ7NVCZ9Rf:-Nb1IOwfAyEJ7NVCZ9Rg:b-lznw64) ([raw file](https://github.com/m-lab/locate/blob/e0d795680267a30783e95608a385783cec76e9c8/memorystore/client.go#L13)):*
> ```Go
> 
> const (
> 	script = `if redis.call('EXISTS', KEYS[1]) == 1
> ```

Do I understand correctly that this is a Lua script interpreted by Redis, and the indexed fields are the positional parameters passed to `Add(..)` below? Looks like this under the covers https://redis.io/commands/eval/

Since we have a combination of languages, please add a comment hinting that this is a Lua script with a link to the docs above.

When we spoke, I was concerned about request latency from the two RTTs. In this case, I agree one operation is better, and I still recommend monitoring for any changes to request latency since this is a more complex operation by redis than I first thought, and Redis will be running on the order of ~60/sec (right?). Your existing histograms should help. As I wrote that I was thinking of the user-visible latency, but if you can see it in the put/histograms it will be user-visible too. Search often looks at millisecond resolution. Do we have plots of e2e user-visible request latency today?
___
*[`memorystore/client.go` line 21 at r1](https://reviewable.io/reviews/m-lab/locate/154#-Nb1GSUN1tiID-It9ejL:-Nb1GSUN1tiID-It9ejM:bydjm60) ([raw file](https://github.com/m-lab/locate/blob/e0d795680267a30783e95608a385783cec76e9c8/memorystore/client.go#L21)):*
> ```Go
> // PutOptions defines the parameters that can be used for PUT operations.
> type PutOptions struct {
> 	Exists bool // Specifies whether the entry should already exist.
> ```

When I consider names, I try to read the operation with options in context to see if the words are self-describing for someone else.

"Put Exists" vs "Put MustExist" or "Put IfExists", etc.
"Put Expire" vs "Put WitExpiration" or "Put AddExpiration", etc.

e.g. These read easily too. 

```
if opts.MustExist {
...


if !ops.WithExpiration {
...

```

What do you think?
___
*[`memorystore/client.go` line 21 at r1](https://reviewable.io/reviews/m-lab/locate/154#-Nb1MuH_-2SXovSHs4H5:-Nb1MuH_-2SXovSHs4H6:bfqezys) ([raw file](https://github.com/m-lab/locate/blob/e0d795680267a30783e95608a385783cec76e9c8/memorystore/client.go#L21)):*
> // Specifies whether the entry must already exist for the put to succeed.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/154)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`heartbeat/heartbeat.go` line 169 at r1](https://reviewable.io/reviews/m-lab/locate/154#-Nb1PbpLDzCkjuyojrLj:-NbBfoJ1B6RXraA8uVpv:bje5pfb) ([raw file](https://github.com/m-lab/locate/blob/e0d795680267a30783e95608a385783cec76e9c8/heartbeat/heartbeat.go#L169)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Just clarifying: prometheus status does not expire? B/c the expiration time is only long enough for heartbeats?

Also clarifying, are there stale prometheus records in redis for retired nodes?
</blockquote></details>

To clarify, the `EXPIRE` command expires the entire key (and its contents), not just a specific field/status. 

Yes, the idea is that this expiry (30s) is renewed whenever the Locate receives an update from the heartbeat (every 10s). Prometheus updates happen less frequently (60s).

I did find a couple entries for retired nodes. I can clean them up if that is helpful.

```
KEYS *yul04*
*5
$45
wehe-mlab1-yul04.mlab-oti.measurement-lab.org
$45
wehe-mlab2-yul04.mlab-oti.measurement-lab.org
$44
ndt-mlab2-yul04.mlab-oti.measurement-lab.org
$44
ndt-mlab3-yul04.mlab-oti.measurement-lab.org
$44
ndt-mlab1-yul04.mlab-oti.measurement-lab.org

HGETALL ndt-mlab2-yul04.mlab-oti.measurement-lab.org
*2
$10
Prometheus
$15
```
___
*[`memorystore/client.go` line 13 at r1](https://reviewable.io/reviews/m-lab/locate/154#-Nb1IOwfAyEJ7NVCZ9Rf:-NbB_DEo6pBujrKz-Pu3:b-p1ih6m) ([raw file](https://github.com/m-lab/locate/blob/e0d795680267a30783e95608a385783cec76e9c8/memorystore/client.go#L13)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Do I understand correctly that this is a Lua script interpreted by Redis, and the indexed fields are the positional parameters passed to `Add(..)` below? Looks like this under the covers https://redis.io/commands/eval/

Since we have a combination of languages, please add a comment hinting that this is a Lua script with a link to the docs above.

When we spoke, I was concerned about request latency from the two RTTs. In this case, I agree one operation is better, and I still recommend monitoring for any changes to request latency since this is a more complex operation by redis than I first thought, and Redis will be running on the order of ~60/sec (right?). Your existing histograms should help. As I wrote that I was thinking of the user-visible latency, but if you can see it in the put/histograms it will be user-visible too. Search often looks at millisecond resolution. Do we have plots of e2e user-visible request latency today?
</blockquote></details>

Correct. I have added a comment describing this.

Can you clarify what you mean by Redis will be running on the order of ~60/sec? 

If you mean that requests are made to Redis every 60 seconds, then that is true of the data that gets imported (e.g., `HGETALL`), but not for the data that gets written (`HSET`), which happens whenever heartbeat instances send health data (every 10s). 

If you mean that Redis runs 60 operations per second, then, at least in production, the number is much greater.



We have histograms to track the latency of Memorystore operations, which will show if this change causes them to become slower.

I'm not sure if by "e2e user-visible request latency" you mean the latency of /nearest operations. If so, I have added metrics to track said latency and a [histogram](https://github.com/m-lab/prometheus-support/pull/992) to visualize it.
___
*[`memorystore/client.go` line 21 at r1](https://reviewable.io/reviews/m-lab/locate/154#-Nb1GSUN1tiID-It9ejL:-NbB_-iX8ONt4fSFpOI3:bwtjo8c) ([raw file](https://github.com/m-lab/locate/blob/e0d795680267a30783e95608a385783cec76e9c8/memorystore/client.go#L21)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

When I consider names, I try to read the operation with options in context to see if the words are self-describing for someone else.

"Put Exists" vs "Put MustExist" or "Put IfExists", etc.
"Put Expire" vs "Put WitExpiration" or "Put AddExpiration", etc.

e.g. These read easily too. 

```
if opts.MustExist {
...


if !ops.WithExpiration {
...

```

What do you think?
</blockquote></details>

Good suggestion. I have renamed these to `MustExist` and `WithExpire`?
___
*[`memorystore/client.go` line 21 at r1](https://reviewable.io/reviews/m-lab/locate/154#-Nb1MuH_-2SXovSHs4H5:-NbB_7TyBsyZw5pk6JFF:bveeaz8) ([raw file](https://github.com/m-lab/locate/blob/e0d795680267a30783e95608a385783cec76e9c8/memorystore/client.go#L21)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

> // Specifies whether the entry must already exist for the put to succeed.
</blockquote></details>

Did you have a separate comment regarding this line?

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/154)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`heartbeat/heartbeat.go` line 169 at r1](https://reviewable.io/reviews/m-lab/locate/154#-Nb1PbpLDzCkjuyojrLj:-NbGMCRz2Xxam8AQvA0_:bmzsd2q) ([raw file](https://github.com/m-lab/locate/blob/e0d795680267a30783e95608a385783cec76e9c8/heartbeat/heartbeat.go#L169)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Thank you for checking.

Please create an issue that describes the problem for the current design that results in stale records in memorystore. Consider changes for a future PR that will ensure that memorystore is eventually purged of these records.
</blockquote></details>

I made [this issue](https://github.com/m-lab/locate/issues/155) for tracking. 
___
*[`memorystore/client.go` line 13 at r1](https://reviewable.io/reviews/m-lab/locate/154#-Nb1IOwfAyEJ7NVCZ9Rf:-NbGFG6IDaP6HI_9M50h:bdyl94k) ([raw file](https://github.com/m-lab/locate/blob/e0d795680267a30783e95608a385783cec76e9c8/memorystore/client.go#L13)):*
>~60 updates/sec was an estimate from ~600 nodes sending heartbeats every 10 sec. iiuc, Redis will be interpreting this small Lua script roughly ~60/sec on average. (Is this about right?)

This is true if we only consider ndt instances. Across experiments, there are ~2000 heartbeat instances sending updates, which results in ~200 operations per second.
___
*[`handler/handler.go` line 191 at r2](https://reviewable.io/reviews/m-lab/locate/154#-NbFFd8V52ouPym6REaK:-NbGJBfz9_H7c3L168wq:bysrael) ([raw file](https://github.com/m-lab/locate/blob/29b8db8d3d628c2a25d21a76a8b1338fa84318c6/handler/handler.go#L191)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

`promhttp.InstrumentHandlerDuration` is also an option if you'd like less logic in the handler. We use this on the https://github.com/m-lab/locate/blob/main/locate.go#L181 handler today.

So, actually, I recommend adding `promhttp.InstrumentHandlerDuration` to all resources:

* /v2/platform/heartbeat
* /v2/platform/monitoring
* /v2/nearest
* /v2/priorty/nearest

This should make this handler logic a little simpler and provide standard metrics for all our resource requests. You can use the same metric with a "resource" and "code" label (see the example documentation for https://pkg.go.dev/github.com/prometheus/client_golang/prometheus/promhttp#InstrumentHandlerDuration )
</blockquote></details>

Ah, yes, this is much better! Changed.

**Review by stephen-soltesz — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/154)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`locate.go` line 180 at r3](https://reviewable.io/reviews/m-lab/locate/154#-NbGOLin20Rf2hPS-u-j:-NbGOLin20Rf2hPS-u-k:b-66f3d) ([raw file](https://github.com/m-lab/locate/blob/e8ea60ee9c5a3884b4650dc99edfd7e208ce07b8/locate.go#L180)):*
> ```Go
> 	// Services report their health to the heartbeat service.
> 	mux.HandleFunc("/v2/platform/heartbeat", promhttp.InstrumentHandlerDuration(
> 		metrics.PrometheusHealthCollectionDuration, http.HandlerFunc(c.Heartbeat)))
> ```

Please ensure there is a "resource" (for the resource path, or named "path" might be simpler) and "code" label (see the example documentation for https://pkg.go.dev/github.com/prometheus/client_golang/prometheus/promhttp#InstrumentHandlerDuration for adding a static label. )

As currently implemented, there will be no separation between the platform and nearest metrics, so it would be like the App Engine latency metrics mixing the two modes. With an additional label, I can imagine a Grafana dashboard variable that allows you to select the path/resource and then reports the latency for requests to that path.
___
*[`memorystore/client.go` line 13 at r1](https://reviewable.io/reviews/m-lab/locate/154#-Nb1IOwfAyEJ7NVCZ9Rf:-NbGNu0j2nzvU-dxt67n:b-rkx2i4) ([raw file](https://github.com/m-lab/locate/blob/e0d795680267a30783e95608a385783cec76e9c8/memorystore/client.go#L13)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

>~60 updates/sec was an estimate from ~600 nodes sending heartbeats every 10 sec. iiuc, Redis will be interpreting this small Lua script roughly ~60/sec on average. (Is this about right?)

This is true if we only consider ndt instances. Across experiments, there are ~2000 heartbeat instances sending updates, which results in ~200 operations per second.
</blockquote></details>

Oooh. That's a lotta Lua.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/154)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`locate.go` line 180 at r3](https://reviewable.io/reviews/m-lab/locate/154#-NbGOLin20Rf2hPS-u-j:-NbVNmT_8BWKKZg4hi6g:bqmjwcz) ([raw file](https://github.com/m-lab/locate/blob/e8ea60ee9c5a3884b4650dc99edfd7e208ce07b8/locate.go#L180)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please ensure there is a "resource" (for the resource path, or named "path" might be simpler) and "code" label (see the example documentation for https://pkg.go.dev/github.com/prometheus/client_golang/prometheus/promhttp#InstrumentHandlerDuration for adding a static label. )

As currently implemented, there will be no separation between the platform and nearest metrics, so it would be like the App Engine latency metrics mixing the two modes. With an additional label, I can imagine a Grafana dashboard variable that allows you to select the path/resource and then reports the latency for requests to that path.
</blockquote></details>

Added.
___
*[`memorystore/client.go` line 13 at r1](https://reviewable.io/reviews/m-lab/locate/154#-Nb1IOwfAyEJ7NVCZ9Rf:-NbVNpfV5am84ft_Xf1R:b8n6aro) ([raw file](https://github.com/m-lab/locate/blob/e0d795680267a30783e95608a385783cec76e9c8/memorystore/client.go#L13)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Oooh. That's a lotta Lua.
</blockquote></details>

Yes. I changed the `EXISTS key` command to `HEXISTS key field` so the operation is done in constant time.

**Review by stephen-soltesz — APPROVED** [review]
No resource abbreviations in the labels, please. Then :lgtm:

> Reviewed 3 of 3 files at r5, 2 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/154#-:-NbVdAqZE20DLPwQ_q5b:b-x7uf87)* status: :shipit: complete! 1 of 1 approvals obtained

___
*[`locate.go` line 180 at r3](https://reviewable.io/reviews/m-lab/locate/154#-NbGOLin20Rf2hPS-u-j:-NbVclX70-1llxqaBtpn:b-uctedk) ([raw file](https://github.com/m-lab/locate/blob/e8ea60ee9c5a3884b4650dc99edfd7e208ce07b8/locate.go#L180)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Added.
</blockquote></details>

Please use the resource name 1:1, no abbreviations.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/154)* status: :shipit: complete! 1 of 1 approvals obtained

___
*[`locate.go` line 180 at r3](https://reviewable.io/reviews/m-lab/locate/154#-NbGOLin20Rf2hPS-u-j:-NbVi--pCvQZ-PZ_L6oB:b-896fiw) ([raw file](https://github.com/m-lab/locate/blob/e8ea60ee9c5a3884b4650dc99edfd7e208ce07b8/locate.go#L180)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please use the resource name 1:1, no abbreviations. 
</blockquote></details>

Done/

**Pull request merged**
