### PR TITLE
Locate: Add histogram for Memorystore request duration

### PR DESCRIPTION
**Pull request by cristinaleonr**
This PR adds a new metric to keep track of how long it takes for the Locate to issue requests to Memorystore.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/locate/152)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
Some small questions.

> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/152#-:-NaTQftT7q7P8ahHU5Ht:b7oob8h)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`memorystore/client.go` line 53 at r1](https://reviewable.io/reviews/m-lab/locate/152#-NaTNn6h-VK7zPDsuTqH:-NaTNn6h-VK7zPDsuTqI:b-3jf7o9) ([raw file](https://github.com/m-lab/locate/blob/11c9be377f4da0647508dac5aa8f3aa00c6484bd/memorystore/client.go#L53)):*
> ```Go
> 	}
> 
> 	metrics.LocateMemorystoreRequestDuration.WithLabelValues("put", field, "OK").Observe(time.Since(t).Seconds())
> ```

Is the same field name every both "expire=true" and "expire=false"? I'm wondering about the potential of mixed use of "OK" and whether that matters.
___
*[`metrics/metrics.go` line 63 at r1](https://reviewable.io/reviews/m-lab/locate/152#-NaTPVpS3YBF70IyQrFC:-NaTPVpS3YBF70IyQrFD:b70l7lq) ([raw file](https://github.com/m-lab/locate/blob/11c9be377f4da0647508dac5aa8f3aa00c6484bd/metrics/metrics.go#L63)):*
> ```Go
> 			Name:    "locate_memorystore_request_duration",
> 			Help:    "A histogram of request latency to Memorystore.",
> 			Buckets: prometheus.LinearBuckets(0, 2, 16), // Buckets from 0 to 30 with steps of size 2.
> ```

This feels a little coarse-grain.

But, I guess we're primarily looking for large outliners..

Did you consider smaller steps in the low end? e.g. like steps before 1 in `prometheus.DefBuckets`?

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/152)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`memorystore/client.go` line 53 at r1](https://reviewable.io/reviews/m-lab/locate/152#-NaTNn6h-VK7zPDsuTqH:-Nag_9IIC65im10tkXmR:b79mk9n) ([raw file](https://github.com/m-lab/locate/blob/11c9be377f4da0647508dac5aa8f3aa00c6484bd/memorystore/client.go#L53)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is the same field name every both "expire=true" and "expire=false"? I'm wondering about the potential of mixed use of "OK" and whether that matters.
</blockquote></details>

I added a suffix to differentiate between "expire=true" and "expire=false".
___
*[`metrics/metrics.go` line 63 at r1](https://reviewable.io/reviews/m-lab/locate/152#-NaTPVpS3YBF70IyQrFC:-Nag_PkP5CO8J2W7rWKM:b-fqkd1m) ([raw file](https://github.com/m-lab/locate/blob/11c9be377f4da0647508dac5aa8f3aa00c6484bd/metrics/metrics.go#L63)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This feels a little coarse-grain.

But, I guess we're primarily looking for large outliners..

Did you consider smaller steps in the low end? e.g. like steps before 1 in `prometheus.DefBuckets`?
</blockquote></details>

Yes, we're primarily looking for request durations that could contribute to the entries' expiration.

I have added smaller steps before 1.

**Review by cristinaleonr — COMMENTED** [review]
@stephen-soltesz PTAL when you get a chance.

> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/152#-:-NahIedR0j7c41cADEK4:bqd4mqo)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

**Review by stephen-soltesz — APPROVED** [review]
Thank you. :lgtm:

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/152#-:-NahJ4U648v8HorqQWBK:bt8gqw2)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by cristinaleonr** [comment]
Related to https://github.com/m-lab/locate/issues/149.

**Pull request merged**
