### PR TITLE
Add functionality to reload registration from siteinfo

### PR DESCRIPTION
**Pull request by cristinaleonr**
This PR adds a loader to reload the registration data from siteinfo every ~24 hours. The loader keeps a copy of the last saved registration and only returns a new one if the data has changed.

The changes were tested by running the heartbeat locally (with a refresh rate of 1min) and pushing a change to siteinfo in sandbox:
```
2023/07/13 16:24:46 updated registration to &{New York US NA  ndt-mlab1-lga0t.mlab-sandbox.measurement-lab.org 40.766 -73.8667 mlab1 lga mlab-sandbox lga0t physical 10g map[ndt/ndt7:[ws:///ndt/v7/download ws:///ndt/v7/upload wss:///ndt/v7/download wss:///ndt/v7/upload]]}
```

This change is [Reviewable](https://reviewable.io/reviews/m-lab/locate/143)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
> Reviewed 3 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/143)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`cmd/heartbeat/main.go` line 118 at r1](https://reviewable.io/reviews/m-lab/locate/143#-N_FKSHh1-8fv45s3Y6X:-N_FKSHh1-8fv45s3Y6Y:bffj5aj) ([raw file](https://github.com/m-lab/locate/blob/5f02a6c85992c8f14bf230ec060c1d361b28c3cd/cmd/heartbeat/main.go#L118)):*
> ```Go
> 			reg, err := ldr.GetRegistration(mainCtx)
> 			if err != nil {
> 				log.Println("could not load registration data")
> ```

Please report the error in the log message.
___
*[`cmd/heartbeat/main.go` line 121 at r1](https://reviewable.io/reviews/m-lab/locate/143#-N_FKhVAEqdUF2e_E5oB:-N_FKhVAEqdUF2e_E5oC:baonhu6) ([raw file](https://github.com/m-lab/locate/blob/5f02a6c85992c8f14bf230ec060c1d361b28c3cd/cmd/heartbeat/main.go#L121)):*
> ```Go
> 			}
> 			if reg != nil {
> 				sendMessage(ws, v2.HeartbeatMessage{Registration: reg}, "registration")
> ```

Just clarifying. I'm used to thinking of the registration message as the first message after opening the ws connection to the Locate. The registration can be sent at any time and Locate does the right thing?
___
*[`cmd/heartbeat/registration.go` line 1 at r1](https://reviewable.io/reviews/m-lab/locate/143#-N_FKzBu11n-ELLYWw-8:-N_FKzBu11n-ELLYWw-9:bo90u9w) ([raw file](https://github.com/m-lab/locate/blob/5f02a6c85992c8f14bf230ec060c1d361b28c3cd/cmd/heartbeat/registration.go#L1)):*
> ```Go
> package main
> ```

I see that heartbeatmsg.go used to be in the `main` package also, but this looks like an `internal` package, no? Does this belong in the main package?
___
*[`cmd/heartbeat/registration.go` line 69 at r1](https://reviewable.io/reviews/m-lab/locate/143#-N_FM2A92XvD0ar14tCZ:-N_FM2A92XvD0ar14tC_:bnk3abr) ([raw file](https://github.com/m-lab/locate/blob/5f02a6c85992c8f14bf230ec060c1d361b28c3cd/cmd/heartbeat/registration.go#L69)):*
> ```Go
> 
> 	if v, ok := registrations[ldr.hostname.String()]; ok {
> 		v.Hostname = ldr.hostname.StringWithService()
> ```

Just observing that the use of `host.Parse` and this convention adds a dependency on the HBS for using M-Lab structured naming.
___
*[`static/configs.go` line 27 at r1](https://reviewable.io/reviews/m-lab/locate/143#-N_FGam42V4E7nyp8D4w:-N_FGam42V4E7nyp8D4x:b-1swypr) ([raw file](https://github.com/m-lab/locate/blob/5f02a6c85992c8f14bf230ec060c1d361b28c3cd/static/configs.go#L27)):*
> ```Go
> 	PrometheusCheckPeriod      = time.Minute
> 	RedisKeyExpirySecs         = 30
> 	RegistrationLoadMin        = 23 * time.Hour
> ```

I fully endorse having an upper bound. However, I don't think we should limit update frequency so much on the lower bound. I might set this to 3hrs and Expected to 12 hrs.

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/143)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`cmd/heartbeat/registration/registration.go` line 78 at r2](https://reviewable.io/reviews/m-lab/locate/143#-N_FndIe03ZmmmiDew3_:-N_FndIe03ZmmmiDew3a:b9fnjq5) ([raw file](https://github.com/m-lab/locate/blob/f7add39a502ff1693e15fa5e5c0be519889d9017/cmd/heartbeat/registration/registration.go#L78)):*
> ```Go
> 		ldr.reg = v
> 		v.Experiment = ldr.exp
> 		v.Services = ldr.svcs
> ```

Please add a prometheus metric of the update time so we can track these updates rolling out (e.g. update time is greater than file time for all pods).

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/143)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`cmd/heartbeat/main.go` line 118 at r1](https://reviewable.io/reviews/m-lab/locate/143#-N_FKSHh1-8fv45s3Y6X:-N_FlNXj-d9J-1GjBxVH:b-896fix) ([raw file](https://github.com/m-lab/locate/blob/5f02a6c85992c8f14bf230ec060c1d361b28c3cd/cmd/heartbeat/main.go#L118)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please report the error in the log message.
</blockquote></details>

Done.
___
*[`cmd/heartbeat/main.go` line 121 at r1](https://reviewable.io/reviews/m-lab/locate/143#-N_FKhVAEqdUF2e_E5oB:-N_Ff2bC9DObpsguxVEV:b-h9kden) ([raw file](https://github.com/m-lab/locate/blob/5f02a6c85992c8f14bf230ec060c1d361b28c3cd/cmd/heartbeat/main.go#L121)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Just clarifying. I'm used to thinking of the registration message as the first message after opening the ws connection to the Locate. The registration can be sent at any time and Locate does the right thing?
</blockquote></details>

Yes, I tested it by changing the latitude for ndt-mlab1-lga0t.mlab-sandbox.measurement-lab.org in sandbox from 40.7667 to 40.7666 and running a local instance of the heartbeat using that hostname.

I see it being received in the logs:
2023/07/13 19:11:54 updated registration to &{New York US NA  ndt-mlab1-lga0t.mlab-sandbox.measurement-lab.org 40.7666 -73.8667 mlab1 lga mlab-sandbox lga0t physical 10g map[ndt/ndt7:[ws:///ndt/v7/download ws:///ndt/v7/upload wss:///ndt/v7/download wss:///ndt/v7/upload]]}

And updated in Redis:
HGETALL ndt-mlab1-lga0t.mlab-sandbox.measurement-lab.org
*6
$12
Registration
$402
{"City":"New York","CountryCode":"US","ContinentCode":"NA","Experiment":"","Hostname":"ndt-mlab1-lga0t.mlab-sandbox.measurement-lab.org", **"Latitude":40.7667,** "Longitude":-73.8667,"Machine":"mlab1","Metro":"lga","Project":"mlab-sandbox","Site":"lga0t","Type":"physical","Uplink":"10g","Services":{"ndt/ndt7":["ws:///ndt/v7/download","ws:///ndt/v7/upload","wss:///ndt/v7/download","wss:///ndt/v7/upload"]}}
$6
Health
$11
{"Score":1}
$10
Prometheus
$15
{"Health":true}

HGETALL ndt-mlab1-lga0t.mlab-sandbox.measurement-lab.org
*6
$12
Registration
$402
{"City":"New York","CountryCode":"US","ContinentCode":"NA","Experiment":"","Hostname":"ndt-mlab1-lga0t.mlab-sandbox.measurement-lab.org", **"Latitude":40.7666,** "Longitude":-73.8667,"Machine":"mlab1","Metro":"lga","Project":"mlab-sandbox","Site":"lga0t","Type":"physical","Uplink":"10g","Services":{"ndt/ndt7":["ws:///ndt/v7/download","ws:///ndt/v7/upload","wss:///ndt/v7/download","wss:///ndt/v7/upload"]}}
$6
Health
$11
{"Score":0}
$10
Prometheus
$15
{"Health":true}
___
*[`static/configs.go` line 27 at r1](https://reviewable.io/reviews/m-lab/locate/143#-N_FGam42V4E7nyp8D4w:-N_FlLYk8OPtsA5z3RNb:b-896fix) ([raw file](https://github.com/m-lab/locate/blob/5f02a6c85992c8f14bf230ec060c1d361b28c3cd/static/configs.go#L27)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I fully endorse having an upper bound. However, I don't think we should limit update frequency so much on the lower bound. I might set this to 3hrs and Expected to 12 hrs.
</blockquote></details>

Done.
___
*[`cmd/heartbeat/registration.go` line 1 at r1](https://reviewable.io/reviews/m-lab/locate/143#-N_FKzBu11n-ELLYWw-8:-N_FlOTA3P49Co3etniX:be13c9c) ([raw file](https://github.com/m-lab/locate/blob/5f02a6c85992c8f14bf230ec060c1d361b28c3cd/cmd/heartbeat/registration.go#L1)):*
Yes, it should be in its own package. Changed!

For reference, this is a comment from an older [PR](https://github.com/m-lab/locate/pull/68) where I had it in its own package :see_no_evil: .
>The remaining logic to load registration messages makes sense under the cmd/heartbeat, b/c that's the only command expected to use this.
___
*[`cmd/heartbeat/registration.go` line 69 at r1](https://reviewable.io/reviews/m-lab/locate/143#-N_FM2A92XvD0ar14tCZ:-N_FgeV6E5nUy9Ti-EUY:bvwfnfw) ([raw file](https://github.com/m-lab/locate/blob/5f02a6c85992c8f14bf230ec060c1d361b28c3cd/cmd/heartbeat/registration.go#L69)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Just observing that the use of `host.Parse` and this convention adds a dependency on the HBS for using M-Lab structured naming.
</blockquote></details>

Yes. This already existed from the [MIG update](https://github.com/m-lab/locate/pull/117/files#diff-f0ea991cef41e035a8f756507f31a1f1b6854f609dbad0e697117cc24d7d22b6).
___
*[`cmd/heartbeat/registration/registration.go` line 78 at r2](https://reviewable.io/reviews/m-lab/locate/143#-N_FndIe03ZmmmiDew3_:-N_G01HH0n3uvtOPJxSl:b-3lf0bz) ([raw file](https://github.com/m-lab/locate/blob/f7add39a502ff1693e15fa5e5c0be519889d9017/cmd/heartbeat/registration/registration.go#L78)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add a prometheus metric of the update time so we can track these updates rolling out (e.g. update time is greater than file time for all pods).
</blockquote></details>

I added one. 

I thought of adding the hostname as a label, but that might increase the cardinality too much. Let me know if you think of any other labels that might be helpful.

**Review by stephen-soltesz — COMMENTED** [review]
One more suggestion and a clarifying question.

> Reviewed 4 of 7 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/143#-:-N_GAGIt4Y-fTt28M5bN:b-ief44g)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`cmd/heartbeat/main.go` line 121 at r1](https://reviewable.io/reviews/m-lab/locate/143#-N_FKhVAEqdUF2e_E5oB:-N_G6a3f23hT61r82tQh:b6c89ne) ([raw file](https://github.com/m-lab/locate/blob/5f02a6c85992c8f14bf230ec060c1d361b28c3cd/cmd/heartbeat/main.go#L121)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Yes, I tested it by changing the latitude for ndt-mlab1-lga0t.mlab-sandbox.measurement-lab.org in sandbox from 40.7667 to 40.7666 and running a local instance of the heartbeat using that hostname.

I see it being received in the logs:
2023/07/13 19:11:54 updated registration to &{New York US NA  ndt-mlab1-lga0t.mlab-sandbox.measurement-lab.org 40.7666 -73.8667 mlab1 lga mlab-sandbox lga0t physical 10g map[ndt/ndt7:[ws:///ndt/v7/download ws:///ndt/v7/upload wss:///ndt/v7/download wss:///ndt/v7/upload]]}

And updated in Redis:
HGETALL ndt-mlab1-lga0t.mlab-sandbox.measurement-lab.org
*6
$12
Registration
$402
{"City":"New York","CountryCode":"US","ContinentCode":"NA","Experiment":"","Hostname":"ndt-mlab1-lga0t.mlab-sandbox.measurement-lab.org", **"Latitude":40.7667,** "Longitude":-73.8667,"Machine":"mlab1","Metro":"lga","Project":"mlab-sandbox","Site":"lga0t","Type":"physical","Uplink":"10g","Services":{"ndt/ndt7":["ws:///ndt/v7/download","ws:///ndt/v7/upload","wss:///ndt/v7/download","wss:///ndt/v7/upload"]}}
$6
Health
$11
{"Score":1}
$10
Prometheus
$15
{"Health":true}

HGETALL ndt-mlab1-lga0t.mlab-sandbox.measurement-lab.org
*6
$12
Registration
$402
{"City":"New York","CountryCode":"US","ContinentCode":"NA","Experiment":"","Hostname":"ndt-mlab1-lga0t.mlab-sandbox.measurement-lab.org", **"Latitude":40.7666,** "Longitude":-73.8667,"Machine":"mlab1","Metro":"lga","Project":"mlab-sandbox","Site":"lga0t","Type":"physical","Uplink":"10g","Services":{"ndt/ndt7":["ws:///ndt/v7/download","ws:///ndt/v7/upload","wss:///ndt/v7/download","wss:///ndt/v7/upload"]}}
$6
Health
$11
{"Score":0}
$10
Prometheus
$15
{"Health":true}


</blockquote></details>

Thank you for confirming.

Just checking - in the example above the `"Score":0` after the update. Is that just a coincidence or does the re-registration reset the score briefly?
___
*[`metrics/metrics.go` line 159 at r3](https://reviewable.io/reviews/m-lab/locate/143#-N_G9SAkDJf2ruyipXbI:-N_G9SAkDJf2ruyipXbJ:brqosaz) ([raw file](https://github.com/m-lab/locate/blob/afe7bacf958c421fe861a90b930adadcc699c208/metrics/metrics.go#L159)):*
> ```Go
> 	// RegistrationUpdateTime tracks the time when a new registration message
> 	// is retrieved from siteinfo.
> 	RegistrationUpdateTime = promauto.NewGaugeVec(
> ```

If there are no labels, prefer `promauto.NewGauge(..)`.
___
*[`cmd/heartbeat/registration.go` line 1 at r1](https://reviewable.io/reviews/m-lab/locate/143#-N_FKzBu11n-ELLYWw-8:-N_G72Gp4GabiCZ_mOxf:b-kp96xl) ([raw file](https://github.com/m-lab/locate/blob/5f02a6c85992c8f14bf230ec060c1d361b28c3cd/cmd/heartbeat/registration.go#L1)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Yes, it should be in its own package. Changed!

For reference, this is a comment from an older [PR](https://github.com/m-lab/locate/pull/68) where I had it in its own package :see_no_evil: .
>The remaining logic to load registration messages makes sense under the cmd/heartbeat, b/c that's the only command expected to use this.

</blockquote></details>

😜 - Thank you. I think my focus was on the parts that didn't belong in the original PR. I've always felt funny about multi-file main packages.
___
*[`cmd/heartbeat/registration/registration.go` line 78 at r2](https://reviewable.io/reviews/m-lab/locate/143#-N_FndIe03ZmmmiDew3_:-N_G8YZD7uTN72ctza6B:bf59ryj) ([raw file](https://github.com/m-lab/locate/blob/f7add39a502ff1693e15fa5e5c0be519889d9017/cmd/heartbeat/registration/registration.go#L78)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

I added one. 

I thought of adding the hostname as a label, but that might increase the cardinality too much. Let me know if you think of any other labels that might be helpful.
</blockquote></details>

The machine name will be added automatically via the pod labels. I can't think of any extra labels.
___
*[`cmd/heartbeat/registration/registration.go` line 81 at r3](https://reviewable.io/reviews/m-lab/locate/143#-N_G9CFM3NDZ8FfrYCzZ:-N_G9CFM3NDZ8FfrYCz_:b-t45ffc) ([raw file](https://github.com/m-lab/locate/blob/afe7bacf958c421fe861a90b930adadcc699c208/cmd/heartbeat/registration/registration.go#L81)):*
> ```Go
> 		v.Experiment = ldr.exp
> 		v.Services = ldr.svcs
> 		metrics.RegistrationUpdateTime.WithLabelValues().Set(float64(time.Now().Unix()))
> ```

nit: if there are no labels prefer the gauge type that does not require `WithLabelValues()`.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/143)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`cmd/heartbeat/main.go` line 121 at r1](https://reviewable.io/reviews/m-lab/locate/143#-N_FKhVAEqdUF2e_E5oB:-N_KuVxfBncMLY-JoguO:b-spxqxv) ([raw file](https://github.com/m-lab/locate/blob/5f02a6c85992c8f14bf230ec060c1d361b28c3cd/cmd/heartbeat/main.go#L121)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Thank you for confirming.

Just checking - in the example above the `"Score":0` after the update. Is that just a coincidence or does the re-registration reset the score briefly?
</blockquote></details>

Hmm good catch. I do not like to believe in coincidences.

I tried to reproduce it 10 times but was not able to do so (it's also possible I didn't check Memorystore quickly enough after update).

I did find a place where we were resetting the whole message locally on registration. I have fixed that now and added a test case.
___
*[`metrics/metrics.go` line 159 at r3](https://reviewable.io/reviews/m-lab/locate/143#-N_G9SAkDJf2ruyipXbI:-N_KuwEh7TAI3boC2iOq:b-e55spc) ([raw file](https://github.com/m-lab/locate/blob/afe7bacf958c421fe861a90b930adadcc699c208/metrics/metrics.go#L159)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

If there are no labels, prefer `promauto.NewGauge(..)`.
</blockquote></details>

Great, done.
___
*[`cmd/heartbeat/registration/registration.go` line 81 at r3](https://reviewable.io/reviews/m-lab/locate/143#-N_G9CFM3NDZ8FfrYCzZ:-N_KuoVE7KxsUoD54wUL:b-a2ujfl) ([raw file](https://github.com/m-lab/locate/blob/afe7bacf958c421fe861a90b930adadcc699c208/cmd/heartbeat/registration/registration.go#L81)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: if there are no labels prefer the gauge type that does not require `WithLabelValues()`.
</blockquote></details>

Changed.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: with additional comment.

> Reviewed 2 of 7 files at r2, 4 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/143#-:-N_L-hiyAnGxYzeQv4VN:b1dxcbh)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`cmd/heartbeat/main.go` line 121 at r1](https://reviewable.io/reviews/m-lab/locate/143#-N_FKhVAEqdUF2e_E5oB:-N_KwKYM75uR3-iLT8nA:bpc858g) ([raw file](https://github.com/m-lab/locate/blob/5f02a6c85992c8f14bf230ec060c1d361b28c3cd/cmd/heartbeat/main.go#L121)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Hmm good catch. I do not like to believe in coincidences.

I tried to reproduce it 10 times but was not able to do so (it's also possible I didn't check Memorystore quickly enough after update).

I did find a place where we were resetting the whole message locally on registration. I have fixed that now and added a test case.
</blockquote></details>

Thank you for confirming and tracking it down. Complex systems can have even more complex behaviors.
___
*[`handler/heartbeat.go` line 70 at r4](https://reviewable.io/reviews/m-lab/locate/143#-N_Kz7Cl5jzTwNnjBd0j:-N_Kz7Cl5jzTwNnjBd0k:b-c3190c) ([raw file](https://github.com/m-lab/locate/blob/831b06cb24e4730064a193945bebc9b31447a430/handler/heartbeat.go#L70)):*
> ```Go
> 					return err
> 				}
> 				if hostname == "" {
> ```

This has a code smell. I think it's downstream of not including the hostname in the original /v2/heartbeat request. It's not blocking. But, I'm having the same twinges I remember having originally.
___
*[`heartbeat/heartbeat.go` line 138 at r4](https://reviewable.io/reviews/m-lab/locate/143#-N_Kx1llCw7iiHZc7ttJ:-N_Kx1llCw7iiHZc7ttK:bd63tgo) ([raw file](https://github.com/m-lab/locate/blob/831b06cb24e4730064a193945bebc9b31447a430/heartbeat/heartbeat.go#L138)):*
> ```Go
> 	defer h.mu.Unlock()
> 
> 	if instance, found := h.instances[hostname]; found {
> ```

Please add a comment motivating this case. I understand this as addressing the `Score:0` scenario.
___
*[`heartbeat/heartbeat_test.go` line 78 at r4](https://reviewable.io/reviews/m-lab/locate/143#-N_KxV2T8z9XMPXSE8_8:-N_KxV2T8z9XMPXSE8_9:b-8fx2ut) ([raw file](https://github.com/m-lab/locate/blob/831b06cb24e4730064a193945bebc9b31447a430/heartbeat/heartbeat_test.go#L78)):*
> ```Go
> 	}
> 
> 	if got.Health.Score != 1.0 {
> ```

:+1:

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/143)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`handler/heartbeat.go` line 70 at r4](https://reviewable.io/reviews/m-lab/locate/143#-N_Kz7Cl5jzTwNnjBd0j:-N_Lapj_8LrL9M4VqkkO:b7ncmhm) ([raw file](https://github.com/m-lab/locate/blob/831b06cb24e4730064a193945bebc9b31447a430/handler/heartbeat.go#L70)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This has a code smell. I think it's downstream of not including the hostname in the original /v2/heartbeat request. It's not blocking. But, I'm having the same twinges I remember having originally.
</blockquote></details>

Noted. IIRC, your previous concern had to do with this being a package variable (it is now local).
___
*[`heartbeat/heartbeat.go` line 138 at r4](https://reviewable.io/reviews/m-lab/locate/143#-N_Kx1llCw7iiHZc7ttJ:-N_LbEskCrcKKtHvr-45:b-896fix) ([raw file](https://github.com/m-lab/locate/blob/831b06cb24e4730064a193945bebc9b31447a430/heartbeat/heartbeat.go#L138)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add a comment motivating this case. I understand this as addressing the `Score:0` scenario.
</blockquote></details>

Done.

**Pull request merged**
