### PR TITLE
Configures Locate to use the new secrets package

### PR DESCRIPTION
**Pull request by nkinkade**
This PR configures the Locate Service to use the new secrets package, which fetches the JWT signer and verify keys from the Google Secret Manager at runtime.

Additionally, this PR removes all of the old project-specific GAE config files in favor of templates for both the locate and locate-platform services.

**IMPORTANT**: In order to not disrupt production services, before the changes in the PR are released, and operator needs to get hold of the current JWT signer and verify keys being used in staging and production, and use them with the new script `management/create_jwt_keys_and_secrets.sh` script. If this isn't done the script will generate new keys and upload them as secrets, which the Locate Service will pick up automatically on restart, breaking the Locate Service.

**NOTE**: The new Cloud Build configuration file makes use of a custom substitution variable, `$_PLATFORM_PROJECT`, which must be set manually in the build trigger for the locate service. I will do this myself, but wanted to point this out.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/locate/56)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/56)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[locate.go, line 45 at r1](https://reviewable.io/reviews/m-lab/locate/56#-MfoHshD63wGrUWZT3nr:-MfoHshD63wGrUWZT3ns:b-cnomll) ([raw file](https://github.com/m-lab/locate/blob/5475ab51004073c11c5332dfb0f1d17379652e4b/locate.go#L45)):*
> ```Go
> 	flag.StringVar(&platform, "platform-project", "", "GCP project for platform machine names")
> 	flag.StringVar(&legacyServer, "legacy-server", proxy.DefaultLegacyServer, "Base URL to mlab-ns server")
> 	flag.StringVar(&locateSignerKey, "locate-signer-key", "locate-service-signer-key", "Name of secret for locate signer key in Secret Manager")
> ```

Since these are "names of keys", please change the flag and variables to include "*-name" and "*Name".
___
*[locate.go, line 61 at r1](https://reviewable.io/reviews/m-lab/locate/56#-MfoJSuq0J_Xsn0cZr7E:-MfoJSuq0J_Xsn0cZr7F:by9ln0s) ([raw file](https://github.com/m-lab/locate/blob/5475ab51004073c11c5332dfb0f1d17379652e4b/locate.go#L61)):*
> ```Go
> 	client, err := secretmanager.NewClient(mainCtx)
> 	rtx.Must(err, "Failed to create Secret Manager client")
> 	defer client.Close()
> ```

Is the client needed after the keys are loaded? This defer will wait until main returns or the process exits.
___
*[locate.go, line 100 at r1](https://reviewable.io/reviews/m-lab/locate/56#-MfoK0Ij2K0SXzPVJvm6:-MfoK0Ij2K0SXzPVJvm7:b-5f07i0) ([raw file](https://github.com/m-lab/locate/blob/5475ab51004073c11c5332dfb0f1d17379652e4b/locate.go#L100)):*
> ```Go
> 	// MONITORING VERIFIER - for access tokens provided by monitoring.
> 	cfg.Name = monitoringVerifyKey
> 	verifier, err := cfg.LoadVerifier(mainCtx, client)
> ```

I'm not sure the best path: it could be helpful to preserve some aspect of the "plural" here that there may be multiple keys. This could be pluralizing `LoadVerifiers` or `monitoringVerifyKeys`... maybe both. The goal is to help make it clear to new readers that there may be multiple keys as part of the resulting verifier.
___
*[cloudbuild/cloudbuild.yaml, line 32 at r1](https://reviewable.io/reviews/m-lab/locate/56#-MfoKPBV8TSBbMvq4KrU:-MfoKPBV8TSBbMvq4KrV:b-qeiqvb) ([raw file](https://github.com/m-lab/locate/blob/5475ab51004073c11c5332dfb0f1d17379652e4b/cloudbuild/cloudbuild.yaml#L32)):*
> ```YAML
>     -e 's/{{PROJECT}}/$PROJECT_ID/g'
>     -e 's/{{PLATFORM_PROJECT}}/$_PLATFORM_PROJECT/'
>     app-platform.yaml
> ```

We have to do this a lot in many repos. Would a little utility help or be redundant? Just thinking out loud - not for this PR.

e.g. 
```
expand PROJECT=$PROJECT_ID PLATFORM_PROJECT=$_PLATFORM_PROJECT app-platform.yaml
```
___
*[cloudbuild/cloudbuild.yaml, line 49 at r1](https://reviewable.io/reviews/m-lab/locate/56#-MfoNDYy4q4Ws5K4PPp4:-MfoNDYy4q4Ws5K4PPp5:be0z60q) ([raw file](https://github.com/m-lab/locate/blob/5475ab51004073c11c5332dfb0f1d17379652e4b/cloudbuild/cloudbuild.yaml#L49)):*
> ```YAML
>     app.yaml
>   - gcloud --project $PROJECT_ID app deploy --promote app.yaml
>   - sed -i -e 's/{{PROJECT}}/$PROJECT_ID/' openapi.yaml
> ```

Why did you change this line?

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/56)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[locate.go, line 45 at r1](https://reviewable.io/reviews/m-lab/locate/56#-MfoHshD63wGrUWZT3nr:-MfsvXw_CpTUqqycQFnl:b-896fix) ([raw file](https://github.com/m-lab/locate/blob/5475ab51004073c11c5332dfb0f1d17379652e4b/locate.go#L45)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Since these are "names of keys", please change the flag and variables to include "*-name" and "*Name".
</blockquote></details>

Done.
___
*[locate.go, line 61 at r1](https://reviewable.io/reviews/m-lab/locate/56#-MfoJSuq0J_Xsn0cZr7E:-MfsxR8p91RyUzA8SlOZ:b-2bl2re) ([raw file](https://github.com/m-lab/locate/blob/5475ab51004073c11c5332dfb0f1d17379652e4b/locate.go#L61)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is the client needed after the keys are loaded? This defer will wait until main returns or the process exits.
</blockquote></details>

It isn't. Thanks for catching this. I moved `client.Close()` further down in the file.
___
*[locate.go, line 100 at r1](https://reviewable.io/reviews/m-lab/locate/56#-MfoK0Ij2K0SXzPVJvm6:-Mfszzw84oTlaAwPh8IR:b2mcw9u) ([raw file](https://github.com/m-lab/locate/blob/5475ab51004073c11c5332dfb0f1d17379652e4b/locate.go#L100)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I'm not sure the best path: it could be helpful to preserve some aspect of the "plural" here that there may be multiple keys. This could be pluralizing `LoadVerifiers` or `monitoringVerifyKeys`... maybe both. The goal is to help make it clear to new readers that there may be multiple keys as part of the resulting verifier.
</blockquote></details>

I see your point. Another point of view is that this name is derived from the function `token.NewVerifier()`, which itself returns a `token.Verifier`. The function doesn't return multiple verifiers, which might itself contain multiple keys. That function takes a slice of keys as a parameter, and returns a single verifier.  If we change the name to `LoadVerifiers`, then the function name is no longer in sync with the `token` package.  I thin there is a reasonable argument for leaving this function name as is.  

Regarding the variable name, it is now `verifySecretName`, which is a singular thing, since once secret will contain all of the possible verify keys. I think this can stay the same too.

What do you think?
___
*[cloudbuild/cloudbuild.yaml, line 32 at r1](https://reviewable.io/reviews/m-lab/locate/56#-MfoKPBV8TSBbMvq4KrU:-Mft09oC9CNLQeNFR5xw:bgbr36t) ([raw file](https://github.com/m-lab/locate/blob/5475ab51004073c11c5332dfb0f1d17379652e4b/cloudbuild/cloudbuild.yaml#L32)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

We have to do this a lot in many repos. Would a little utility help or be redundant? Just thinking out loud - not for this PR.

e.g. 
```
expand PROJECT=$PROJECT_ID PLATFORM_PROJECT=$_PLATFORM_PROJECT app-platform.yaml
```
</blockquote></details>

Agreed, and moving it to some package in the m-lab/go repo would standardize the way anyone might implement this on their own. It would also  standardize the template variable name, and it would remove a bit of shell scripting that we have smattered all over the place.
___
*[cloudbuild/cloudbuild.yaml, line 49 at r1](https://reviewable.io/reviews/m-lab/locate/56#-MfoNDYy4q4Ws5K4PPp4:-Mft0YgvEPec2Gn7aYFj:b5vnk5g) ([raw file](https://github.com/m-lab/locate/blob/5475ab51004073c11c5332dfb0f1d17379652e4b/cloudbuild/cloudbuild.yaml#L49)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Why did you change this line?
</blockquote></details>

Sorry. This seemingly meaningless change is a vestige of an earlier iteration of my changes to this file that involved a much more complicated build step. The previous iteration I'm referring to was the one where I was leveraging CB's integration of Secret Manager, which requires `bash` as the entrypoint, which was requiring a lot more backbending involving mixed use of single and double quotes.  To make that all work things were wrapped at the outside level with single quotes, and double quotes inside. I changed this line to use single quotes for no other reason than to use the same convention everywhere in the file: single outside quotes.

**Review by nkinkade — COMMENTED** [review]
@stephen-soltesz: changes pushed and comments added. PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/56#-:-MftG9pz8XhOwF7hGvHt:b-1tatj2)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: with final requests.

> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/56#-:-MftKXhx4JBvNiRs8ssp:b3ut3kl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @nkinkade)

___
*[locate.go, line 100 at r1](https://reviewable.io/reviews/m-lab/locate/56#-MfoK0Ij2K0SXzPVJvm6:-MftJa782rk3BrWgp8QT:b-wzvvt3) ([raw file](https://github.com/m-lab/locate/blob/5475ab51004073c11c5332dfb0f1d17379652e4b/locate.go#L100)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I see your point. Another point of view is that this name is derived from the function `token.NewVerifier()`, which itself returns a `token.Verifier`. The function doesn't return multiple verifiers, which might itself contain multiple keys. That function takes a slice of keys as a parameter, and returns a single verifier.  If we change the name to `LoadVerifiers`, then the function name is no longer in sync with the `token` package.  I thin there is a reasonable argument for leaving this function name as is.  

Regarding the variable name, it is now `verifySecretName`, which is a singular thing, since once secret will contain all of the possible verify keys. I think this can stay the same too.

What do you think?
</blockquote></details>

Hmm, I see your points. There are multiple things here (name, secret, versions, verifier keys, the resulting verifier), more than what I was thinking, Would you be willing to simply add a comment highlighting the sequence? i.e. name -> secret -> versions -> keys -> verifier.
___
*[cloudbuild/cloudbuild.yaml, line 49 at r1](https://reviewable.io/reviews/m-lab/locate/56#-MfoNDYy4q4Ws5K4PPp4:-MftKIG3D9uYmSW-BB6l:b-2t884i) ([raw file](https://github.com/m-lab/locate/blob/5475ab51004073c11c5332dfb0f1d17379652e4b/cloudbuild/cloudbuild.yaml#L49)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Sorry. This seemingly meaningless change is a vestige of an earlier iteration of my changes to this file that involved a much more complicated build step. The previous iteration I'm referring to was the one where I was leveraging CB's integration of Secret Manager, which requires `bash` as the entrypoint, which was requiring a lot more backbending involving mixed use of single and double quotes.  To make that all work things were wrapped at the outside level with single quotes, and double quotes inside. I changed this line to use single quotes for no other reason than to use the same convention everywhere in the file: single outside quotes. 
</blockquote></details>

ooh. I didn't even notice the quotes. I was wondering about putting the `sed` command before the comment rather than after. Would you move it after the comment again? (I'm thinking it just groups the related actions together for the openapi).

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/56)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[locate.go, line 100 at r1](https://reviewable.io/reviews/m-lab/locate/56#-MfoK0Ij2K0SXzPVJvm6:-MftOi8NC-q1wlqygYTu:b-896fix) ([raw file](https://github.com/m-lab/locate/blob/5475ab51004073c11c5332dfb0f1d17379652e4b/locate.go#L100)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Hmm, I see your points. There are multiple things here (name, secret, versions, verifier keys, the resulting verifier), more than what I was thinking, Would you be willing to simply add a comment highlighting the sequence? i.e. name -> secret -> versions -> keys -> verifier.
</blockquote></details>

Done.
___
*[cloudbuild/cloudbuild.yaml, line 49 at r1](https://reviewable.io/reviews/m-lab/locate/56#-MfoNDYy4q4Ws5K4PPp4:-MftPCSJ9XAxGAtO5gWO:bivnba0) ([raw file](https://github.com/m-lab/locate/blob/5475ab51004073c11c5332dfb0f1d17379652e4b/cloudbuild/cloudbuild.yaml#L49)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

ooh. I didn't even notice the quotes. I was wondering about putting the `sed` command before the comment rather than after. Would you move it after the comment again? (I'm thinking it just groups the related actions together for the openapi).
</blockquote></details>

Ah, I misunderstood your question. I have no idea why I moved that `sed` statement, but I moved it back after the comment.

**Pull request merged**
