### PR TITLE
Add Target.Hostname for v3 names

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds a new field to the Locate API's `Target.Hostname`.

This change fixes an issue with inconsistent machine and service names for autonodes, should remain backward compatible, and allows end to end monitoring of autonode targets.
* See: https://github.com/m-lab/locate/issues/195

Previously, the `heartbeat.Locator.Nearest` returns a set of API `v2.Targets`, which included a field for the machine name and URLs for the services. Recovering the service name required either parsing one of the URLs or reconstructing the service name from the request experiment and machine name. This change simplifies the handler logic by preserving the machine and service name. Now, the handler logic uses the service `Hostname` unmodified from node heartbeat `Registration` to `Nearest` results. The `getAccessToken` still uses the machine and `getURLs` uses the service name rather than reconstructing it.

Similarly, the monitoring target used the reconstruct the service name from the machine name. Now we use the subject name without modification for v3 and preserve v2 compatibility.

This change was verified in sandbox using the following checks:

* [Query using autonode site](https://locate-dot-mlab-sandbox.appspot.com/v2/nearest/ndt/ndt7?site=oma396982)
* [Query using standard site](https://locate-dot-mlab-sandbox.appspot.com/v2/nearest/ndt/ndt7?site=lga0t)
* monitoring-token query (below)
* monitoring-token results have correct audience and subject names for backward compatibility (below)

Monitoring token query:
```
# for autonode
{
  ...
  "results": [
    {
      "machine": "ndt-oma396982-2248791f.mlab.sandbox.measurement-lab.org",
      "hostname": "ndt-oma396982-2248791f.mlab.sandbox.measurement-lab.org",
      "urls": {
        "ws:///ndt/v7/download": "ws://ndt-oma396982-2248791f.mlab.sandbox.measurement-lab.org/ndt/v7/download?access_token=...",
        "ws:///ndt/v7/upload": "ws://ndt-oma396982-2248791f.mlab.sandbox.measurement-lab.org/ndt/v7/upload?access_token=...",
        "wss:///ndt/v7/download": "wss://ndt-oma396982-2248791f.mlab.sandbox.measurement-lab.org/ndt/v7/download?access_token=...",
        "wss:///ndt/v7/upload": "wss://ndt-oma396982-2248791f.mlab.sandbox.measurement-lab.org/ndt/v7/upload?access_token=..."
      }
    }
  ]
}
# for platform node
{
  ...
  "results": [
    {
      "machine": "mlab1-lga1t.mlab-sandbox.measurement-lab.org",
      "hostname": "ndt-mlab1-lga1t.mlab-sandbox.measurement-lab.org",
      "urls": {
        "ws:///ndt/v7/download": "ws://ndt-mlab1-lga1t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=...",
        "ws:///ndt/v7/upload": "ws://ndt-mlab1-lga1t.mlab-sandbox.measurement-lab.org/ndt/v7/upload?access_token=...",
        "wss:///ndt/v7/download": "wss://ndt-mlab1-lga1t.mlab-sandbox.measurement-lab.org/ndt/v7/download?access_token=...",
        "wss:///ndt/v7/upload": "wss://ndt-mlab1-lga1t.mlab-sandbox.measurement-lab.org/ndt/v7/upload?access_token=..."
      }
    }
  ]
}
```

Monitoring token results:
```
$ echo eyJhdWQiOlsibWxhYjEtbGdhMXQubWxhYi1zYW5kYm94Lm1lYXN1cmVtZW50LWxhYi5vcmciXSwiZXhwIjoxNzI3MzgwMTc3LCJpc3MiOiJsb2NhdGUiLCJqdGkiOiI5NGE1ZTdkZC0zZWE2LTRlY2EtOGZmMC02YTM2MGY0NGM3OWQiLCJzdWIiOiJtb25pdG9yaW5nIn0 | base64 -d
{"aud":["mlab1-lga1t.mlab-sandbox.measurement-lab.org"],"exp":1727380177,"iss":"locate","jti":"94a5e7dd-3ea6-4eca-8ff0-6a360f44c79d","sub":"monitoring"}base64: invalid input
(base) [[sandbox-soltesz-v3-machines ?] soltesz@Stephens-iMac:~/src/github.com/m-lab/locate>
$ echo eyJhdWQiOlsibmR0LW9tYTM5Njk4Mi0yMjQ4NzkxZi5tbGFiLnNhbmRib3gubWVhc3VyZW1lbnQtbGFiLm9yZyJdLCJleHAiOjE3MjczNzk4OTMsImlzcyI6ImxvY2F0ZSIsImp0aSI6ImE5MTM3NjQ2LTgyN2YtNDIyMy05NWU5LTFkZTdlZWM3OTVjNiIsInN1YiI6Im1vbml0b3JpbmcifQ | base64 -d
{"aud":["ndt-oma396982-2248791f.mlab.sandbox.measurement-lab.org"],"exp":1727379893,"iss":"locate","jti":"a9137646-827f-4223-95e9-1de7eec795c6","sub":"monitoring"}
```

Using pending changes to the autonode, ndt-server, and ndt-client-go, I have verified end to end that token verification works as intended for user and monitoring clients within sandbox nodes (managed and autonodes). 
* [Require ndt7 tokens and static verifier key](https://github.com/m-lab/autonode/pull/18)
* [Use flagx.ArgsFromEnv with logging off](https://github.com/m-lab/ndt7-client-go/pull/100)
* [Use flagx.StringFile for autocert.hostname and token.machine](https://github.com/m-lab/ndt-server/pull/406)

This change is [Reviewable](https://reviewable.io/reviews/m-lab/locate/196)

### CODE REVIEW

**Review by cristinaleonr — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/196#-:-O82k1OEA1CZJTerGkef:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`heartbeat/location.go` line 92 at r2](https://reviewable.io/reviews/m-lab/locate/196#-O82jpSl7ASTF4_6Z2pj:-O82jpSl7ASTF4_6Z2pk:b-at2zz) ([raw file](https://github.com/m-lab/locate/blob/e7d9861db6974b85f139803cd542690cb9f52c43/heartbeat/location.go#L92)):*
> ```Go
> 	result := pickTargets(service, sites)
> 
> 	if len(result.Targets) == 0 {
> ```

Hmm, lol! I wonder if one of these checks was meant to be `result.Targets == nil`

**Review by stephen-soltesz — COMMENTED** [review]
Thank you!

> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/196#-:-O83R4zu3udkth1clOy3:b-9755fn)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`heartbeat/location.go` line 92 at r2](https://reviewable.io/reviews/m-lab/locate/196#-O82jpSl7ASTF4_6Z2pj:-O83R8gaDddC1vhT0GP3:b-nvp0th) ([raw file](https://github.com/m-lab/locate/blob/e7d9861db6974b85f139803cd542690cb9f52c43/heartbeat/location.go#L92)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Hmm, lol! I wonder if one of these checks was meant to be `result.Targets == nil`
</blockquote></details>

Could be - fortunately, even that case would be equivalent too

```
package main

import "fmt"

func main() {
	fmt.Println(len([]string(nil)), len([]string{}))
}
```

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/196)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`heartbeat/location.go` line 92 at r2](https://reviewable.io/reviews/m-lab/locate/196#-O82jpSl7ASTF4_6Z2pj:-O83Yfh3DLwWma2VdeLK:b-xitvsd) ([raw file](https://github.com/m-lab/locate/blob/e7d9861db6974b85f139803cd542690cb9f52c43/heartbeat/location.go#L92)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Could be - fortunately, even that case would be equivalent too

```
package main

import "fmt"

func main() {
	fmt.Println(len([]string(nil)), len([]string{}))
}
```
</blockquote></details>

Agh, I meant `result == nil`

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/locate/196)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`heartbeat/location.go` line 92 at r2](https://reviewable.io/reviews/m-lab/locate/196#-O82jpSl7ASTF4_6Z2pj:-O87OlDT9r_DdX5k125J:b-z4wbm3) ([raw file](https://github.com/m-lab/locate/blob/e7d9861db6974b85f139803cd542690cb9f52c43/heartbeat/location.go#L92)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Agh, I meant `result == nil`
</blockquote></details>

Good question - currently the implementation makes it impossible for `result` to be nil. I will trust that for now.

**Pull request merged**
